package com.rlogin.dao.mapper.gjj;

import com.rlogin.domain.gjj.GjjDetail;
import com.rlogin.domain.gjj.GjjDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GjjDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int countByExample(GjjDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int deleteByExample(GjjDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int insert(GjjDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int insertSelective(GjjDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    List<GjjDetail> selectByExample(GjjDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    GjjDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") GjjDetail record, @Param("example") GjjDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByExample(@Param("record") GjjDetail record, @Param("example") GjjDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByPrimaryKeySelective(GjjDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByPrimaryKey(GjjDetail record);
}