package com.rlogin.dao.mapper.gjj;

import com.rlogin.domain.gjj.GjjLoanStatus;
import com.rlogin.domain.gjj.GjjLoanStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GjjLoanStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int countByExample(GjjLoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int deleteByExample(GjjLoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int insert(GjjLoanStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int insertSelective(GjjLoanStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    List<GjjLoanStatus> selectByExample(GjjLoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    GjjLoanStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") GjjLoanStatus record, @Param("example") GjjLoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int updateByExample(@Param("record") GjjLoanStatus record, @Param("example") GjjLoanStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int updateByPrimaryKeySelective(GjjLoanStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    int updateByPrimaryKey(GjjLoanStatus record);
}