package com.rlogin.dao.mapper.gjj;

import com.rlogin.domain.gjj.GjjRepayPlan;
import com.rlogin.domain.gjj.GjjRepayPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GjjRepayPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int countByExample(GjjRepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int deleteByExample(GjjRepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int insert(GjjRepayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int insertSelective(GjjRepayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    List<GjjRepayPlan> selectByExample(GjjRepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    GjjRepayPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") GjjRepayPlan record, @Param("example") GjjRepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int updateByExample(@Param("record") GjjRepayPlan record, @Param("example") GjjRepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int updateByPrimaryKeySelective(GjjRepayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    int updateByPrimaryKey(GjjRepayPlan record);
}