package com.rlogin.dao.mapper.gjj;

import com.rlogin.domain.gjj.GjjRepayPlanDetail;
import com.rlogin.domain.gjj.GjjRepayPlanDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GjjRepayPlanDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int countByExample(GjjRepayPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int deleteByExample(GjjRepayPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int insert(GjjRepayPlanDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int insertSelective(GjjRepayPlanDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    List<GjjRepayPlanDetail> selectByExample(GjjRepayPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    GjjRepayPlanDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") GjjRepayPlanDetail record, @Param("example") GjjRepayPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByExample(@Param("record") GjjRepayPlanDetail record, @Param("example") GjjRepayPlanDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByPrimaryKeySelective(GjjRepayPlanDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    int updateByPrimaryKey(GjjRepayPlanDetail record);
}