package com.rlogin.dao.mapper.gjj;

import com.rlogin.domain.gjj.GjjUser;
import com.rlogin.domain.gjj.GjjUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GjjUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int countByExample(GjjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int deleteByExample(GjjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int insert(GjjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int insertSelective(GjjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    List<GjjUser> selectByExample(GjjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    GjjUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") GjjUser record, @Param("example") GjjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int updateByExample(@Param("record") GjjUser record, @Param("example") GjjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int updateByPrimaryKeySelective(GjjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    int updateByPrimaryKey(GjjUser record);
}