package com.rlogin.domain.gjj;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GjjAccDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public GjjAccDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNull() {
            addCriterion("user_acc_id is null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNotNull() {
            addCriterion("user_acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdEqualTo(String value) {
            addCriterion("user_acc_id =", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotEqualTo(String value) {
            addCriterion("user_acc_id <>", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThan(String value) {
            addCriterion("user_acc_id >", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_acc_id >=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThan(String value) {
            addCriterion("user_acc_id <", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThanOrEqualTo(String value) {
            addCriterion("user_acc_id <=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLike(String value) {
            addCriterion("user_acc_id like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotLike(String value) {
            addCriterion("user_acc_id not like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIn(List<String> values) {
            addCriterion("user_acc_id in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotIn(List<String> values) {
            addCriterion("user_acc_id not in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdBetween(String value1, String value2) {
            addCriterion("user_acc_id between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotBetween(String value1, String value2) {
            addCriterion("user_acc_id not between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(Integer value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(Integer value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(Integer value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(Integer value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(Integer value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<Integer> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<Integer> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(Integer value1, Integer value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andTeamAccIsNull() {
            addCriterion("team_acc is null");
            return (Criteria) this;
        }

        public Criteria andTeamAccIsNotNull() {
            addCriterion("team_acc is not null");
            return (Criteria) this;
        }

        public Criteria andTeamAccEqualTo(String value) {
            addCriterion("team_acc =", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccNotEqualTo(String value) {
            addCriterion("team_acc <>", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccGreaterThan(String value) {
            addCriterion("team_acc >", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccGreaterThanOrEqualTo(String value) {
            addCriterion("team_acc >=", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccLessThan(String value) {
            addCriterion("team_acc <", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccLessThanOrEqualTo(String value) {
            addCriterion("team_acc <=", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccLike(String value) {
            addCriterion("team_acc like", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccNotLike(String value) {
            addCriterion("team_acc not like", value, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccIn(List<String> values) {
            addCriterion("team_acc in", values, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccNotIn(List<String> values) {
            addCriterion("team_acc not in", values, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccBetween(String value1, String value2) {
            addCriterion("team_acc between", value1, value2, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamAccNotBetween(String value1, String value2) {
            addCriterion("team_acc not between", value1, value2, "teamAcc");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNull() {
            addCriterion("team_name is null");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNotNull() {
            addCriterion("team_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeamNameEqualTo(String value) {
            addCriterion("team_name =", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotEqualTo(String value) {
            addCriterion("team_name <>", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThan(String value) {
            addCriterion("team_name >", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThanOrEqualTo(String value) {
            addCriterion("team_name >=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThan(String value) {
            addCriterion("team_name <", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThanOrEqualTo(String value) {
            addCriterion("team_name <=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLike(String value) {
            addCriterion("team_name like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotLike(String value) {
            addCriterion("team_name not like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameIn(List<String> values) {
            addCriterion("team_name in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotIn(List<String> values) {
            addCriterion("team_name not in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameBetween(String value1, String value2) {
            addCriterion("team_name between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotBetween(String value1, String value2) {
            addCriterion("team_name not between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeIsNull() {
            addCriterion("acc_create_time is null");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeIsNotNull() {
            addCriterion("acc_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeEqualTo(Date value) {
            addCriterion("acc_create_time =", value, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeNotEqualTo(Date value) {
            addCriterion("acc_create_time <>", value, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeGreaterThan(Date value) {
            addCriterion("acc_create_time >", value, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("acc_create_time >=", value, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeLessThan(Date value) {
            addCriterion("acc_create_time <", value, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("acc_create_time <=", value, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeIn(List<Date> values) {
            addCriterion("acc_create_time in", values, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeNotIn(List<Date> values) {
            addCriterion("acc_create_time not in", values, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeBetween(Date value1, Date value2) {
            addCriterion("acc_create_time between", value1, value2, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("acc_create_time not between", value1, value2, "accCreateTime");
            return (Criteria) this;
        }

        public Criteria andAccStatusIsNull() {
            addCriterion("acc_status is null");
            return (Criteria) this;
        }

        public Criteria andAccStatusIsNotNull() {
            addCriterion("acc_status is not null");
            return (Criteria) this;
        }

        public Criteria andAccStatusEqualTo(Integer value) {
            addCriterion("acc_status =", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusNotEqualTo(Integer value) {
            addCriterion("acc_status <>", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusGreaterThan(Integer value) {
            addCriterion("acc_status >", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("acc_status >=", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusLessThan(Integer value) {
            addCriterion("acc_status <", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusLessThanOrEqualTo(Integer value) {
            addCriterion("acc_status <=", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusIn(List<Integer> values) {
            addCriterion("acc_status in", values, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusNotIn(List<Integer> values) {
            addCriterion("acc_status not in", values, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusBetween(Integer value1, Integer value2) {
            addCriterion("acc_status between", value1, value2, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("acc_status not between", value1, value2, "accStatus");
            return (Criteria) this;
        }

        public Criteria andUserMContributeIsNull() {
            addCriterion("user_m_contribute is null");
            return (Criteria) this;
        }

        public Criteria andUserMContributeIsNotNull() {
            addCriterion("user_m_contribute is not null");
            return (Criteria) this;
        }

        public Criteria andUserMContributeEqualTo(Double value) {
            addCriterion("user_m_contribute =", value, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeNotEqualTo(Double value) {
            addCriterion("user_m_contribute <>", value, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeGreaterThan(Double value) {
            addCriterion("user_m_contribute >", value, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeGreaterThanOrEqualTo(Double value) {
            addCriterion("user_m_contribute >=", value, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeLessThan(Double value) {
            addCriterion("user_m_contribute <", value, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeLessThanOrEqualTo(Double value) {
            addCriterion("user_m_contribute <=", value, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeIn(List<Double> values) {
            addCriterion("user_m_contribute in", values, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeNotIn(List<Double> values) {
            addCriterion("user_m_contribute not in", values, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeBetween(Double value1, Double value2) {
            addCriterion("user_m_contribute between", value1, value2, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andUserMContributeNotBetween(Double value1, Double value2) {
            addCriterion("user_m_contribute not between", value1, value2, "userMContribute");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(Double value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(Double value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(Double value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(Double value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(Double value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(Double value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<Double> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<Double> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(Double value1, Double value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(Double value1, Double value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNull() {
            addCriterion("last_time is null");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNotNull() {
            addCriterion("last_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastTimeEqualTo(Date value) {
            addCriterionForJDBCDate("last_time =", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("last_time <>", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("last_time >", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_time >=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThan(Date value) {
            addCriterionForJDBCDate("last_time <", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_time <=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeIn(List<Date> values) {
            addCriterionForJDBCDate("last_time in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("last_time not in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_time between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_time not between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andUserRateIsNull() {
            addCriterion("user_rate is null");
            return (Criteria) this;
        }

        public Criteria andUserRateIsNotNull() {
            addCriterion("user_rate is not null");
            return (Criteria) this;
        }

        public Criteria andUserRateEqualTo(Double value) {
            addCriterion("user_rate =", value, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateNotEqualTo(Double value) {
            addCriterion("user_rate <>", value, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateGreaterThan(Double value) {
            addCriterion("user_rate >", value, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateGreaterThanOrEqualTo(Double value) {
            addCriterion("user_rate >=", value, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateLessThan(Double value) {
            addCriterion("user_rate <", value, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateLessThanOrEqualTo(Double value) {
            addCriterion("user_rate <=", value, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateIn(List<Double> values) {
            addCriterion("user_rate in", values, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateNotIn(List<Double> values) {
            addCriterion("user_rate not in", values, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateBetween(Double value1, Double value2) {
            addCriterion("user_rate between", value1, value2, "userRate");
            return (Criteria) this;
        }

        public Criteria andUserRateNotBetween(Double value1, Double value2) {
            addCriterion("user_rate not between", value1, value2, "userRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateIsNull() {
            addCriterion("team_rate is null");
            return (Criteria) this;
        }

        public Criteria andTeamRateIsNotNull() {
            addCriterion("team_rate is not null");
            return (Criteria) this;
        }

        public Criteria andTeamRateEqualTo(Double value) {
            addCriterion("team_rate =", value, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateNotEqualTo(Double value) {
            addCriterion("team_rate <>", value, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateGreaterThan(Double value) {
            addCriterion("team_rate >", value, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateGreaterThanOrEqualTo(Double value) {
            addCriterion("team_rate >=", value, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateLessThan(Double value) {
            addCriterion("team_rate <", value, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateLessThanOrEqualTo(Double value) {
            addCriterion("team_rate <=", value, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateIn(List<Double> values) {
            addCriterion("team_rate in", values, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateNotIn(List<Double> values) {
            addCriterion("team_rate not in", values, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateBetween(Double value1, Double value2) {
            addCriterion("team_rate between", value1, value2, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamRateNotBetween(Double value1, Double value2) {
            addCriterion("team_rate not between", value1, value2, "teamRate");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeIsNull() {
            addCriterion("team_create_time is null");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeIsNotNull() {
            addCriterion("team_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeEqualTo(Date value) {
            addCriterion("team_create_time =", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeNotEqualTo(Date value) {
            addCriterion("team_create_time <>", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeGreaterThan(Date value) {
            addCriterion("team_create_time >", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("team_create_time >=", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeLessThan(Date value) {
            addCriterion("team_create_time <", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("team_create_time <=", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeIn(List<Date> values) {
            addCriterion("team_create_time in", values, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeNotIn(List<Date> values) {
            addCriterion("team_create_time not in", values, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeBetween(Date value1, Date value2) {
            addCriterion("team_create_time between", value1, value2, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("team_create_time not between", value1, value2, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamStatusIsNull() {
            addCriterion("team_status is null");
            return (Criteria) this;
        }

        public Criteria andTeamStatusIsNotNull() {
            addCriterion("team_status is not null");
            return (Criteria) this;
        }

        public Criteria andTeamStatusEqualTo(Integer value) {
            addCriterion("team_status =", value, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusNotEqualTo(Integer value) {
            addCriterion("team_status <>", value, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusGreaterThan(Integer value) {
            addCriterion("team_status >", value, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("team_status >=", value, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusLessThan(Integer value) {
            addCriterion("team_status <", value, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusLessThanOrEqualTo(Integer value) {
            addCriterion("team_status <=", value, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusIn(List<Integer> values) {
            addCriterion("team_status in", values, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusNotIn(List<Integer> values) {
            addCriterion("team_status not in", values, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusBetween(Integer value1, Integer value2) {
            addCriterion("team_status between", value1, value2, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andTeamStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("team_status not between", value1, value2, "teamStatus");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("bank is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("bank is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(String value) {
            addCriterion("bank =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(String value) {
            addCriterion("bank <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(String value) {
            addCriterion("bank >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(String value) {
            addCriterion("bank >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(String value) {
            addCriterion("bank <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(String value) {
            addCriterion("bank <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLike(String value) {
            addCriterion("bank like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotLike(String value) {
            addCriterion("bank not like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<String> values) {
            addCriterion("bank in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<String> values) {
            addCriterion("bank not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(String value1, String value2) {
            addCriterion("bank between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(String value1, String value2) {
            addCriterion("bank not between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNull() {
            addCriterion("parse_time is null");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNotNull() {
            addCriterion("parse_time is not null");
            return (Criteria) this;
        }

        public Criteria andParseTimeEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time =", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time <>", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("parse_time >", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time >=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThan(Date value) {
            addCriterionForJDBCDate("parse_time <", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time <=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeIn(List<Date> values) {
            addCriterionForJDBCDate("parse_time in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("parse_time not in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("parse_time between", value1, value2, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("parse_time not between", value1, value2, "parseTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated do_not_delete_during_merge Sun May 17 22:57:30 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_acc_detail
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}