package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjAccDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.Id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String userAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.product_code
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Integer productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.team_acc
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String teamAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.team_name
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.acc_create_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Date accCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.acc_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Integer accStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.user_m_contribute
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Double userMContribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.balance
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.last_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.user_rate
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Double userRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.team_rate
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Double teamRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.team_create_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Date teamCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.team_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Integer teamStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.bank
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_acc_detail.parse_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Date parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.Id
     *
     * @return the value of gjj_acc_detail.Id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.Id
     *
     * @param id the value for gjj_acc_detail.Id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.user_acc_id
     *
     * @return the value of gjj_acc_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getUserAccId() {
        return userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.user_acc_id
     *
     * @param userAccId the value for gjj_acc_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setUserAccId(String userAccId) {
        this.userAccId = userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.product_code
     *
     * @return the value of gjj_acc_detail.product_code
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.product_code
     *
     * @param productCode the value for gjj_acc_detail.product_code
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.team_acc
     *
     * @return the value of gjj_acc_detail.team_acc
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getTeamAcc() {
        return teamAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.team_acc
     *
     * @param teamAcc the value for gjj_acc_detail.team_acc
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTeamAcc(String teamAcc) {
        this.teamAcc = teamAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.team_name
     *
     * @return the value of gjj_acc_detail.team_name
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.team_name
     *
     * @param teamName the value for gjj_acc_detail.team_name
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.acc_create_time
     *
     * @return the value of gjj_acc_detail.acc_create_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Date getAccCreateTime() {
        return accCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.acc_create_time
     *
     * @param accCreateTime the value for gjj_acc_detail.acc_create_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setAccCreateTime(Date accCreateTime) {
        this.accCreateTime = accCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.acc_status
     *
     * @return the value of gjj_acc_detail.acc_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Integer getAccStatus() {
        return accStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.acc_status
     *
     * @param accStatus the value for gjj_acc_detail.acc_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setAccStatus(Integer accStatus) {
        this.accStatus = accStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.user_m_contribute
     *
     * @return the value of gjj_acc_detail.user_m_contribute
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Double getUserMContribute() {
        return userMContribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.user_m_contribute
     *
     * @param userMContribute the value for gjj_acc_detail.user_m_contribute
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setUserMContribute(Double userMContribute) {
        this.userMContribute = userMContribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.balance
     *
     * @return the value of gjj_acc_detail.balance
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.balance
     *
     * @param balance the value for gjj_acc_detail.balance
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.last_time
     *
     * @return the value of gjj_acc_detail.last_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.last_time
     *
     * @param lastTime the value for gjj_acc_detail.last_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.user_rate
     *
     * @return the value of gjj_acc_detail.user_rate
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Double getUserRate() {
        return userRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.user_rate
     *
     * @param userRate the value for gjj_acc_detail.user_rate
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setUserRate(Double userRate) {
        this.userRate = userRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.team_rate
     *
     * @return the value of gjj_acc_detail.team_rate
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Double getTeamRate() {
        return teamRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.team_rate
     *
     * @param teamRate the value for gjj_acc_detail.team_rate
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTeamRate(Double teamRate) {
        this.teamRate = teamRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.team_create_time
     *
     * @return the value of gjj_acc_detail.team_create_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Date getTeamCreateTime() {
        return teamCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.team_create_time
     *
     * @param teamCreateTime the value for gjj_acc_detail.team_create_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTeamCreateTime(Date teamCreateTime) {
        this.teamCreateTime = teamCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.team_status
     *
     * @return the value of gjj_acc_detail.team_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Integer getTeamStatus() {
        return teamStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.team_status
     *
     * @param teamStatus the value for gjj_acc_detail.team_status
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTeamStatus(Integer teamStatus) {
        this.teamStatus = teamStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.bank
     *
     * @return the value of gjj_acc_detail.bank
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.bank
     *
     * @param bank the value for gjj_acc_detail.bank
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_acc_detail.parse_time
     *
     * @return the value of gjj_acc_detail.parse_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Date getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_acc_detail.parse_time
     *
     * @param parseTime the value for gjj_acc_detail.parse_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setParseTime(Date parseTime) {
        this.parseTime = parseTime;
    }
}