package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.Id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String userAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.team_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String teamAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.team_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.user_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String userAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.user_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.id_card
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.trade_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.trade_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_detail.parse_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.Id
     *
     * @return the value of gjj_detail.Id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.Id
     *
     * @param id the value for gjj_detail.Id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.user_acc_id
     *
     * @return the value of gjj_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getUserAccId() {
        return userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.user_acc_id
     *
     * @param userAccId the value for gjj_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setUserAccId(String userAccId) {
        this.userAccId = userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.team_acc
     *
     * @return the value of gjj_detail.team_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTeamAcc() {
        return teamAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.team_acc
     *
     * @param teamAcc the value for gjj_detail.team_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTeamAcc(String teamAcc) {
        this.teamAcc = teamAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.team_name
     *
     * @return the value of gjj_detail.team_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.team_name
     *
     * @param teamName the value for gjj_detail.team_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.user_acc
     *
     * @return the value of gjj_detail.user_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getUserAcc() {
        return userAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.user_acc
     *
     * @param userAcc the value for gjj_detail.user_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setUserAcc(String userAcc) {
        this.userAcc = userAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.user_name
     *
     * @return the value of gjj_detail.user_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.user_name
     *
     * @param userName the value for gjj_detail.user_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.id_card
     *
     * @return the value of gjj_detail.id_card
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.id_card
     *
     * @param idCard the value for gjj_detail.id_card
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.trade_time
     *
     * @return the value of gjj_detail.trade_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.trade_time
     *
     * @param tradeTime the value for gjj_detail.trade_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.type
     *
     * @return the value of gjj_detail.type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.type
     *
     * @param type the value for gjj_detail.type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.trade_amount
     *
     * @return the value of gjj_detail.trade_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.trade_amount
     *
     * @param tradeAmount the value for gjj_detail.trade_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTradeAmount(Double tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.balance
     *
     * @return the value of gjj_detail.balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.balance
     *
     * @param balance the value for gjj_detail.balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_detail.parse_time
     *
     * @return the value of gjj_detail.parse_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_detail.parse_time
     *
     * @param parseTime the value for gjj_detail.parse_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setParseTime(Date parseTime) {
        this.parseTime = parseTime;
    }
}