package com.rlogin.domain.gjj;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GjjLoanStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public GjjLoanStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNull() {
            addCriterion("user_acc_id is null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNotNull() {
            addCriterion("user_acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdEqualTo(String value) {
            addCriterion("user_acc_id =", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotEqualTo(String value) {
            addCriterion("user_acc_id <>", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThan(String value) {
            addCriterion("user_acc_id >", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_acc_id >=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThan(String value) {
            addCriterion("user_acc_id <", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThanOrEqualTo(String value) {
            addCriterion("user_acc_id <=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLike(String value) {
            addCriterion("user_acc_id like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotLike(String value) {
            addCriterion("user_acc_id not like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIn(List<String> values) {
            addCriterion("user_acc_id in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotIn(List<String> values) {
            addCriterion("user_acc_id not in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdBetween(String value1, String value2) {
            addCriterion("user_acc_id between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotBetween(String value1, String value2) {
            addCriterion("user_acc_id not between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeIsNull() {
            addCriterion("id_care_type is null");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeIsNotNull() {
            addCriterion("id_care_type is not null");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeEqualTo(String value) {
            addCriterion("id_care_type =", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeNotEqualTo(String value) {
            addCriterion("id_care_type <>", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeGreaterThan(String value) {
            addCriterion("id_care_type >", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeGreaterThanOrEqualTo(String value) {
            addCriterion("id_care_type >=", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeLessThan(String value) {
            addCriterion("id_care_type <", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeLessThanOrEqualTo(String value) {
            addCriterion("id_care_type <=", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeLike(String value) {
            addCriterion("id_care_type like", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeNotLike(String value) {
            addCriterion("id_care_type not like", value, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeIn(List<String> values) {
            addCriterion("id_care_type in", values, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeNotIn(List<String> values) {
            addCriterion("id_care_type not in", values, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeBetween(String value1, String value2) {
            addCriterion("id_care_type between", value1, value2, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCareTypeNotBetween(String value1, String value2) {
            addCriterion("id_care_type not between", value1, value2, "idCareType");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andLoanAccIsNull() {
            addCriterion("loan_acc is null");
            return (Criteria) this;
        }

        public Criteria andLoanAccIsNotNull() {
            addCriterion("loan_acc is not null");
            return (Criteria) this;
        }

        public Criteria andLoanAccEqualTo(String value) {
            addCriterion("loan_acc =", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotEqualTo(String value) {
            addCriterion("loan_acc <>", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccGreaterThan(String value) {
            addCriterion("loan_acc >", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccGreaterThanOrEqualTo(String value) {
            addCriterion("loan_acc >=", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccLessThan(String value) {
            addCriterion("loan_acc <", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccLessThanOrEqualTo(String value) {
            addCriterion("loan_acc <=", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccLike(String value) {
            addCriterion("loan_acc like", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotLike(String value) {
            addCriterion("loan_acc not like", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccIn(List<String> values) {
            addCriterion("loan_acc in", values, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotIn(List<String> values) {
            addCriterion("loan_acc not in", values, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccBetween(String value1, String value2) {
            addCriterion("loan_acc between", value1, value2, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotBetween(String value1, String value2) {
            addCriterion("loan_acc not between", value1, value2, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNull() {
            addCriterion("loan_amount is null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNotNull() {
            addCriterion("loan_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountEqualTo(Double value) {
            addCriterion("loan_amount =", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotEqualTo(Double value) {
            addCriterion("loan_amount <>", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThan(Double value) {
            addCriterion("loan_amount >", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("loan_amount >=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThan(Double value) {
            addCriterion("loan_amount <", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThanOrEqualTo(Double value) {
            addCriterion("loan_amount <=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIn(List<Double> values) {
            addCriterion("loan_amount in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotIn(List<Double> values) {
            addCriterion("loan_amount not in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountBetween(Double value1, Double value2) {
            addCriterion("loan_amount between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotBetween(Double value1, Double value2) {
            addCriterion("loan_amount not between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsIsNull() {
            addCriterion("loan_months is null");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsIsNotNull() {
            addCriterion("loan_months is not null");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsEqualTo(Integer value) {
            addCriterion("loan_months =", value, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsNotEqualTo(Integer value) {
            addCriterion("loan_months <>", value, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsGreaterThan(Integer value) {
            addCriterion("loan_months >", value, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_months >=", value, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsLessThan(Integer value) {
            addCriterion("loan_months <", value, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsLessThanOrEqualTo(Integer value) {
            addCriterion("loan_months <=", value, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsIn(List<Integer> values) {
            addCriterion("loan_months in", values, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsNotIn(List<Integer> values) {
            addCriterion("loan_months not in", values, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsBetween(Integer value1, Integer value2) {
            addCriterion("loan_months between", value1, value2, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanMonthsNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_months not between", value1, value2, "loanMonths");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIsNull() {
            addCriterion("loan_type is null");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIsNotNull() {
            addCriterion("loan_type is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTypeEqualTo(String value) {
            addCriterion("loan_type =", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotEqualTo(String value) {
            addCriterion("loan_type <>", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeGreaterThan(String value) {
            addCriterion("loan_type >", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeGreaterThanOrEqualTo(String value) {
            addCriterion("loan_type >=", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLessThan(String value) {
            addCriterion("loan_type <", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLessThanOrEqualTo(String value) {
            addCriterion("loan_type <=", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLike(String value) {
            addCriterion("loan_type like", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotLike(String value) {
            addCriterion("loan_type not like", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIn(List<String> values) {
            addCriterion("loan_type in", values, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotIn(List<String> values) {
            addCriterion("loan_type not in", values, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeBetween(String value1, String value2) {
            addCriterion("loan_type between", value1, value2, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotBetween(String value1, String value2) {
            addCriterion("loan_type not between", value1, value2, "loanType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNull() {
            addCriterion("house_type is null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNotNull() {
            addCriterion("house_type is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeEqualTo(String value) {
            addCriterion("house_type =", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotEqualTo(String value) {
            addCriterion("house_type <>", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThan(String value) {
            addCriterion("house_type >", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("house_type >=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThan(String value) {
            addCriterion("house_type <", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThanOrEqualTo(String value) {
            addCriterion("house_type <=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLike(String value) {
            addCriterion("house_type like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotLike(String value) {
            addCriterion("house_type not like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIn(List<String> values) {
            addCriterion("house_type in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotIn(List<String> values) {
            addCriterion("house_type not in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeBetween(String value1, String value2) {
            addCriterion("house_type between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotBetween(String value1, String value2) {
            addCriterion("house_type not between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("bank is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("bank is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(String value) {
            addCriterion("bank =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(String value) {
            addCriterion("bank <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(String value) {
            addCriterion("bank >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(String value) {
            addCriterion("bank >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(String value) {
            addCriterion("bank <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(String value) {
            addCriterion("bank <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLike(String value) {
            addCriterion("bank like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotLike(String value) {
            addCriterion("bank not like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<String> values) {
            addCriterion("bank in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<String> values) {
            addCriterion("bank not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(String value1, String value2) {
            addCriterion("bank between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(String value1, String value2) {
            addCriterion("bank not between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andLoanStatusIsNull() {
            addCriterion("loan_status is null");
            return (Criteria) this;
        }

        public Criteria andLoanStatusIsNotNull() {
            addCriterion("loan_status is not null");
            return (Criteria) this;
        }

        public Criteria andLoanStatusEqualTo(String value) {
            addCriterion("loan_status =", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusNotEqualTo(String value) {
            addCriterion("loan_status <>", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusGreaterThan(String value) {
            addCriterion("loan_status >", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusGreaterThanOrEqualTo(String value) {
            addCriterion("loan_status >=", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusLessThan(String value) {
            addCriterion("loan_status <", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusLessThanOrEqualTo(String value) {
            addCriterion("loan_status <=", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusLike(String value) {
            addCriterion("loan_status like", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusNotLike(String value) {
            addCriterion("loan_status not like", value, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusIn(List<String> values) {
            addCriterion("loan_status in", values, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusNotIn(List<String> values) {
            addCriterion("loan_status not in", values, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusBetween(String value1, String value2) {
            addCriterion("loan_status between", value1, value2, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andLoanStatusNotBetween(String value1, String value2) {
            addCriterion("loan_status not between", value1, value2, "loanStatus");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNull() {
            addCriterion("parse_time is null");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNotNull() {
            addCriterion("parse_time is not null");
            return (Criteria) this;
        }

        public Criteria andParseTimeEqualTo(Date value) {
            addCriterion("parse_time =", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotEqualTo(Date value) {
            addCriterion("parse_time <>", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThan(Date value) {
            addCriterion("parse_time >", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time >=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThan(Date value) {
            addCriterion("parse_time <", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThanOrEqualTo(Date value) {
            addCriterion("parse_time <=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeIn(List<Date> values) {
            addCriterion("parse_time in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotIn(List<Date> values) {
            addCriterion("parse_time not in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeBetween(Date value1, Date value2) {
            addCriterion("parse_time between", value1, value2, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotBetween(Date value1, Date value2) {
            addCriterion("parse_time not between", value1, value2, "parseTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_loan_status
     *
     * @mbggenerated do_not_delete_during_merge Sun May 17 22:57:30 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_loan_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}