package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjLoan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.Id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.user_acc_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String userAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_company
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanUserCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_phone
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanUserPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_gjj_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanUserGjjAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_gjj_m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanUserGjjMAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_gjj_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanUserGjjStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanUserBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanUserAddAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_user_add_blance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanUserAddBlance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanSpouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanSpouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_company
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanSpouseCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_phone
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanSpousePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_gjj_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanSpouseGjjAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_gjj_m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanSpouseGjjMAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_gjj_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanSpouseGjjStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanSpouseBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String loanSpouseAddAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_spouse_add_blance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanSpouseAddBlance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double mAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.m_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double mRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_begin_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date loanBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_end_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date loanEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.last_plan
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date lastPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.last_real
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date lastReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.acc_bank
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String accBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.left_month
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Integer leftMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.m_month
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String mMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.current_term_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double currentTermAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.current_term_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date currentTermTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.current_term_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double currentTermRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.current_term_principal
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double currentTermPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.repay_type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String repayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.over_m
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Integer overM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.overdue_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double overdueRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.over_due_principal
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double overDuePrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.over_should_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double overShouldRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.overdue_real_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double overdueRealRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.trust_loan_type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String trustLoanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.trust_loan_use
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String trustLoanUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.trust_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date trustTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.trust_loan_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String trustLoanAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.trust_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String trustAddAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.trust_spouse_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String trustSpouseAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.trust_spouse_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private String trustSpouseAddAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.loan_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double loanSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.principal_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double principalSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.rate_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double rateSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.normal_balance_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double normalBalanceSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.overdue_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Double overdueSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan.parse_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    private Date parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.Id
     *
     * @return the value of gjj_loan.Id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.Id
     *
     * @param id the value for gjj_loan.Id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.user_acc_id
     *
     * @return the value of gjj_loan.user_acc_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getUserAccId() {
        return userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.user_acc_id
     *
     * @param userAccId the value for gjj_loan.user_acc_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setUserAccId(String userAccId) {
        this.userAccId = userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_acc
     *
     * @return the value of gjj_loan.loan_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanAcc() {
        return loanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_acc
     *
     * @param loanAcc the value for gjj_loan.loan_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanAcc(String loanAcc) {
        this.loanAcc = loanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_name
     *
     * @return the value of gjj_loan.loan_user_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanUserName() {
        return loanUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_name
     *
     * @param loanUserName the value for gjj_loan.loan_user_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserName(String loanUserName) {
        this.loanUserName = loanUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_id
     *
     * @return the value of gjj_loan.loan_user_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanUserId() {
        return loanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_id
     *
     * @param loanUserId the value for gjj_loan.loan_user_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserId(String loanUserId) {
        this.loanUserId = loanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_company
     *
     * @return the value of gjj_loan.loan_user_company
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanUserCompany() {
        return loanUserCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_company
     *
     * @param loanUserCompany the value for gjj_loan.loan_user_company
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserCompany(String loanUserCompany) {
        this.loanUserCompany = loanUserCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_phone
     *
     * @return the value of gjj_loan.loan_user_phone
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanUserPhone() {
        return loanUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_phone
     *
     * @param loanUserPhone the value for gjj_loan.loan_user_phone
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserPhone(String loanUserPhone) {
        this.loanUserPhone = loanUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_gjj_acc
     *
     * @return the value of gjj_loan.loan_user_gjj_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanUserGjjAcc() {
        return loanUserGjjAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_gjj_acc
     *
     * @param loanUserGjjAcc the value for gjj_loan.loan_user_gjj_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserGjjAcc(String loanUserGjjAcc) {
        this.loanUserGjjAcc = loanUserGjjAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_gjj_m_amount
     *
     * @return the value of gjj_loan.loan_user_gjj_m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanUserGjjMAmount() {
        return loanUserGjjMAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_gjj_m_amount
     *
     * @param loanUserGjjMAmount the value for gjj_loan.loan_user_gjj_m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserGjjMAmount(Double loanUserGjjMAmount) {
        this.loanUserGjjMAmount = loanUserGjjMAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_gjj_status
     *
     * @return the value of gjj_loan.loan_user_gjj_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanUserGjjStatus() {
        return loanUserGjjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_gjj_status
     *
     * @param loanUserGjjStatus the value for gjj_loan.loan_user_gjj_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserGjjStatus(String loanUserGjjStatus) {
        this.loanUserGjjStatus = loanUserGjjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_balance
     *
     * @return the value of gjj_loan.loan_user_balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanUserBalance() {
        return loanUserBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_balance
     *
     * @param loanUserBalance the value for gjj_loan.loan_user_balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserBalance(Double loanUserBalance) {
        this.loanUserBalance = loanUserBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_add_acc
     *
     * @return the value of gjj_loan.loan_user_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanUserAddAcc() {
        return loanUserAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_add_acc
     *
     * @param loanUserAddAcc the value for gjj_loan.loan_user_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserAddAcc(String loanUserAddAcc) {
        this.loanUserAddAcc = loanUserAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_user_add_blance
     *
     * @return the value of gjj_loan.loan_user_add_blance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanUserAddBlance() {
        return loanUserAddBlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_user_add_blance
     *
     * @param loanUserAddBlance the value for gjj_loan.loan_user_add_blance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanUserAddBlance(Double loanUserAddBlance) {
        this.loanUserAddBlance = loanUserAddBlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_name
     *
     * @return the value of gjj_loan.loan_spouse_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanSpouseName() {
        return loanSpouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_name
     *
     * @param loanSpouseName the value for gjj_loan.loan_spouse_name
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseName(String loanSpouseName) {
        this.loanSpouseName = loanSpouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_id
     *
     * @return the value of gjj_loan.loan_spouse_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanSpouseId() {
        return loanSpouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_id
     *
     * @param loanSpouseId the value for gjj_loan.loan_spouse_id
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseId(String loanSpouseId) {
        this.loanSpouseId = loanSpouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_company
     *
     * @return the value of gjj_loan.loan_spouse_company
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanSpouseCompany() {
        return loanSpouseCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_company
     *
     * @param loanSpouseCompany the value for gjj_loan.loan_spouse_company
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseCompany(String loanSpouseCompany) {
        this.loanSpouseCompany = loanSpouseCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_phone
     *
     * @return the value of gjj_loan.loan_spouse_phone
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanSpousePhone() {
        return loanSpousePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_phone
     *
     * @param loanSpousePhone the value for gjj_loan.loan_spouse_phone
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpousePhone(String loanSpousePhone) {
        this.loanSpousePhone = loanSpousePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_gjj_acc
     *
     * @return the value of gjj_loan.loan_spouse_gjj_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanSpouseGjjAcc() {
        return loanSpouseGjjAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_gjj_acc
     *
     * @param loanSpouseGjjAcc the value for gjj_loan.loan_spouse_gjj_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseGjjAcc(String loanSpouseGjjAcc) {
        this.loanSpouseGjjAcc = loanSpouseGjjAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_gjj_m_amount
     *
     * @return the value of gjj_loan.loan_spouse_gjj_m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanSpouseGjjMAmount() {
        return loanSpouseGjjMAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_gjj_m_amount
     *
     * @param loanSpouseGjjMAmount the value for gjj_loan.loan_spouse_gjj_m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseGjjMAmount(Double loanSpouseGjjMAmount) {
        this.loanSpouseGjjMAmount = loanSpouseGjjMAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_gjj_status
     *
     * @return the value of gjj_loan.loan_spouse_gjj_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanSpouseGjjStatus() {
        return loanSpouseGjjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_gjj_status
     *
     * @param loanSpouseGjjStatus the value for gjj_loan.loan_spouse_gjj_status
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseGjjStatus(String loanSpouseGjjStatus) {
        this.loanSpouseGjjStatus = loanSpouseGjjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_balance
     *
     * @return the value of gjj_loan.loan_spouse_balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanSpouseBalance() {
        return loanSpouseBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_balance
     *
     * @param loanSpouseBalance the value for gjj_loan.loan_spouse_balance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseBalance(Double loanSpouseBalance) {
        this.loanSpouseBalance = loanSpouseBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_add_acc
     *
     * @return the value of gjj_loan.loan_spouse_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getLoanSpouseAddAcc() {
        return loanSpouseAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_add_acc
     *
     * @param loanSpouseAddAcc the value for gjj_loan.loan_spouse_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseAddAcc(String loanSpouseAddAcc) {
        this.loanSpouseAddAcc = loanSpouseAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_spouse_add_blance
     *
     * @return the value of gjj_loan.loan_spouse_add_blance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanSpouseAddBlance() {
        return loanSpouseAddBlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_spouse_add_blance
     *
     * @param loanSpouseAddBlance the value for gjj_loan.loan_spouse_add_blance
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSpouseAddBlance(Double loanSpouseAddBlance) {
        this.loanSpouseAddBlance = loanSpouseAddBlance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_amount
     *
     * @return the value of gjj_loan.loan_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_amount
     *
     * @param loanAmount the value for gjj_loan.loan_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanAmount(Double loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_rate
     *
     * @return the value of gjj_loan.loan_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanRate() {
        return loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_rate
     *
     * @param loanRate the value for gjj_loan.loan_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanRate(Double loanRate) {
        this.loanRate = loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.m_amount
     *
     * @return the value of gjj_loan.m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getmAmount() {
        return mAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.m_amount
     *
     * @param mAmount the value for gjj_loan.m_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setmAmount(Double mAmount) {
        this.mAmount = mAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.m_rate
     *
     * @return the value of gjj_loan.m_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getmRate() {
        return mRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.m_rate
     *
     * @param mRate the value for gjj_loan.m_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setmRate(Double mRate) {
        this.mRate = mRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_begin_time
     *
     * @return the value of gjj_loan.loan_begin_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getLoanBeginTime() {
        return loanBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_begin_time
     *
     * @param loanBeginTime the value for gjj_loan.loan_begin_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanBeginTime(Date loanBeginTime) {
        this.loanBeginTime = loanBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_end_time
     *
     * @return the value of gjj_loan.loan_end_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getLoanEndTime() {
        return loanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_end_time
     *
     * @param loanEndTime the value for gjj_loan.loan_end_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanEndTime(Date loanEndTime) {
        this.loanEndTime = loanEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.last_plan
     *
     * @return the value of gjj_loan.last_plan
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getLastPlan() {
        return lastPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.last_plan
     *
     * @param lastPlan the value for gjj_loan.last_plan
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLastPlan(Date lastPlan) {
        this.lastPlan = lastPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.last_real
     *
     * @return the value of gjj_loan.last_real
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getLastReal() {
        return lastReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.last_real
     *
     * @param lastReal the value for gjj_loan.last_real
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLastReal(Date lastReal) {
        this.lastReal = lastReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.acc_bank
     *
     * @return the value of gjj_loan.acc_bank
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getAccBank() {
        return accBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.acc_bank
     *
     * @param accBank the value for gjj_loan.acc_bank
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setAccBank(String accBank) {
        this.accBank = accBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.left_month
     *
     * @return the value of gjj_loan.left_month
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Integer getLeftMonth() {
        return leftMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.left_month
     *
     * @param leftMonth the value for gjj_loan.left_month
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLeftMonth(Integer leftMonth) {
        this.leftMonth = leftMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.m_month
     *
     * @return the value of gjj_loan.m_month
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getmMonth() {
        return mMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.m_month
     *
     * @param mMonth the value for gjj_loan.m_month
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setmMonth(String mMonth) {
        this.mMonth = mMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.current_term_amount
     *
     * @return the value of gjj_loan.current_term_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getCurrentTermAmount() {
        return currentTermAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.current_term_amount
     *
     * @param currentTermAmount the value for gjj_loan.current_term_amount
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setCurrentTermAmount(Double currentTermAmount) {
        this.currentTermAmount = currentTermAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.current_term_time
     *
     * @return the value of gjj_loan.current_term_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getCurrentTermTime() {
        return currentTermTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.current_term_time
     *
     * @param currentTermTime the value for gjj_loan.current_term_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setCurrentTermTime(Date currentTermTime) {
        this.currentTermTime = currentTermTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.current_term_rate
     *
     * @return the value of gjj_loan.current_term_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getCurrentTermRate() {
        return currentTermRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.current_term_rate
     *
     * @param currentTermRate the value for gjj_loan.current_term_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setCurrentTermRate(Double currentTermRate) {
        this.currentTermRate = currentTermRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.current_term_principal
     *
     * @return the value of gjj_loan.current_term_principal
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getCurrentTermPrincipal() {
        return currentTermPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.current_term_principal
     *
     * @param currentTermPrincipal the value for gjj_loan.current_term_principal
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setCurrentTermPrincipal(Double currentTermPrincipal) {
        this.currentTermPrincipal = currentTermPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.repay_type
     *
     * @return the value of gjj_loan.repay_type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.repay_type
     *
     * @param repayType the value for gjj_loan.repay_type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setRepayType(String repayType) {
        this.repayType = repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.over_m
     *
     * @return the value of gjj_loan.over_m
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Integer getOverM() {
        return overM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.over_m
     *
     * @param overM the value for gjj_loan.over_m
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOverM(Integer overM) {
        this.overM = overM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.overdue_rate
     *
     * @return the value of gjj_loan.overdue_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getOverdueRate() {
        return overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.overdue_rate
     *
     * @param overdueRate the value for gjj_loan.overdue_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOverdueRate(Double overdueRate) {
        this.overdueRate = overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.over_due_principal
     *
     * @return the value of gjj_loan.over_due_principal
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getOverDuePrincipal() {
        return overDuePrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.over_due_principal
     *
     * @param overDuePrincipal the value for gjj_loan.over_due_principal
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOverDuePrincipal(Double overDuePrincipal) {
        this.overDuePrincipal = overDuePrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.over_should_rate
     *
     * @return the value of gjj_loan.over_should_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getOverShouldRate() {
        return overShouldRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.over_should_rate
     *
     * @param overShouldRate the value for gjj_loan.over_should_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOverShouldRate(Double overShouldRate) {
        this.overShouldRate = overShouldRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.overdue_real_rate
     *
     * @return the value of gjj_loan.overdue_real_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getOverdueRealRate() {
        return overdueRealRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.overdue_real_rate
     *
     * @param overdueRealRate the value for gjj_loan.overdue_real_rate
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOverdueRealRate(Double overdueRealRate) {
        this.overdueRealRate = overdueRealRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.trust_loan_type
     *
     * @return the value of gjj_loan.trust_loan_type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTrustLoanType() {
        return trustLoanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.trust_loan_type
     *
     * @param trustLoanType the value for gjj_loan.trust_loan_type
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTrustLoanType(String trustLoanType) {
        this.trustLoanType = trustLoanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.trust_loan_use
     *
     * @return the value of gjj_loan.trust_loan_use
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTrustLoanUse() {
        return trustLoanUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.trust_loan_use
     *
     * @param trustLoanUse the value for gjj_loan.trust_loan_use
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTrustLoanUse(String trustLoanUse) {
        this.trustLoanUse = trustLoanUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.trust_time
     *
     * @return the value of gjj_loan.trust_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getTrustTime() {
        return trustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.trust_time
     *
     * @param trustTime the value for gjj_loan.trust_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTrustTime(Date trustTime) {
        this.trustTime = trustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.trust_loan_acc
     *
     * @return the value of gjj_loan.trust_loan_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTrustLoanAcc() {
        return trustLoanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.trust_loan_acc
     *
     * @param trustLoanAcc the value for gjj_loan.trust_loan_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTrustLoanAcc(String trustLoanAcc) {
        this.trustLoanAcc = trustLoanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.trust_add_acc
     *
     * @return the value of gjj_loan.trust_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTrustAddAcc() {
        return trustAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.trust_add_acc
     *
     * @param trustAddAcc the value for gjj_loan.trust_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTrustAddAcc(String trustAddAcc) {
        this.trustAddAcc = trustAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.trust_spouse_acc
     *
     * @return the value of gjj_loan.trust_spouse_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTrustSpouseAcc() {
        return trustSpouseAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.trust_spouse_acc
     *
     * @param trustSpouseAcc the value for gjj_loan.trust_spouse_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTrustSpouseAcc(String trustSpouseAcc) {
        this.trustSpouseAcc = trustSpouseAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.trust_spouse_add_acc
     *
     * @return the value of gjj_loan.trust_spouse_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public String getTrustSpouseAddAcc() {
        return trustSpouseAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.trust_spouse_add_acc
     *
     * @param trustSpouseAddAcc the value for gjj_loan.trust_spouse_add_acc
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setTrustSpouseAddAcc(String trustSpouseAddAcc) {
        this.trustSpouseAddAcc = trustSpouseAddAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.loan_sum
     *
     * @return the value of gjj_loan.loan_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getLoanSum() {
        return loanSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.loan_sum
     *
     * @param loanSum the value for gjj_loan.loan_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setLoanSum(Double loanSum) {
        this.loanSum = loanSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.principal_sum
     *
     * @return the value of gjj_loan.principal_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getPrincipalSum() {
        return principalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.principal_sum
     *
     * @param principalSum the value for gjj_loan.principal_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setPrincipalSum(Double principalSum) {
        this.principalSum = principalSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.rate_sum
     *
     * @return the value of gjj_loan.rate_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getRateSum() {
        return rateSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.rate_sum
     *
     * @param rateSum the value for gjj_loan.rate_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setRateSum(Double rateSum) {
        this.rateSum = rateSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.normal_balance_sum
     *
     * @return the value of gjj_loan.normal_balance_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getNormalBalanceSum() {
        return normalBalanceSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.normal_balance_sum
     *
     * @param normalBalanceSum the value for gjj_loan.normal_balance_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setNormalBalanceSum(Double normalBalanceSum) {
        this.normalBalanceSum = normalBalanceSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.overdue_sum
     *
     * @return the value of gjj_loan.overdue_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Double getOverdueSum() {
        return overdueSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.overdue_sum
     *
     * @param overdueSum the value for gjj_loan.overdue_sum
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setOverdueSum(Double overdueSum) {
        this.overdueSum = overdueSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan.parse_time
     *
     * @return the value of gjj_loan.parse_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public Date getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan.parse_time
     *
     * @param parseTime the value for gjj_loan.parse_time
     *
     * @mbggenerated Sun May 17 22:57:30 CST 2015
     */
    public void setParseTime(Date parseTime) {
        this.parseTime = parseTime;
    }
}