package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjRepayPlanDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.Id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.loan_id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private String loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.loan_term
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Integer loanTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.loan_Principal
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double loanPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.loan_rate
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double loanRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.loan_penalty
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double loanPenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.loan_sum
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double loanSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.loan_left
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double loanLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.plan_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.remark
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan_detail.parse_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.Id
     *
     * @return the value of gjj_repay_plan_detail.Id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.Id
     *
     * @param id the value for gjj_repay_plan_detail.Id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.loan_id
     *
     * @return the value of gjj_repay_plan_detail.loan_id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.loan_id
     *
     * @param loanId the value for gjj_repay_plan_detail.loan_id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.loan_term
     *
     * @return the value of gjj_repay_plan_detail.loan_term
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Integer getLoanTerm() {
        return loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.loan_term
     *
     * @param loanTerm the value for gjj_repay_plan_detail.loan_term
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoanTerm(Integer loanTerm) {
        this.loanTerm = loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.loan_Principal
     *
     * @return the value of gjj_repay_plan_detail.loan_Principal
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getLoanPrincipal() {
        return loanPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.loan_Principal
     *
     * @param loanPrincipal the value for gjj_repay_plan_detail.loan_Principal
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoanPrincipal(Double loanPrincipal) {
        this.loanPrincipal = loanPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.loan_rate
     *
     * @return the value of gjj_repay_plan_detail.loan_rate
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getLoanRate() {
        return loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.loan_rate
     *
     * @param loanRate the value for gjj_repay_plan_detail.loan_rate
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoanRate(Double loanRate) {
        this.loanRate = loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.loan_penalty
     *
     * @return the value of gjj_repay_plan_detail.loan_penalty
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getLoanPenalty() {
        return loanPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.loan_penalty
     *
     * @param loanPenalty the value for gjj_repay_plan_detail.loan_penalty
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoanPenalty(Double loanPenalty) {
        this.loanPenalty = loanPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.loan_sum
     *
     * @return the value of gjj_repay_plan_detail.loan_sum
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getLoanSum() {
        return loanSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.loan_sum
     *
     * @param loanSum the value for gjj_repay_plan_detail.loan_sum
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoanSum(Double loanSum) {
        this.loanSum = loanSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.loan_left
     *
     * @return the value of gjj_repay_plan_detail.loan_left
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getLoanLeft() {
        return loanLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.loan_left
     *
     * @param loanLeft the value for gjj_repay_plan_detail.loan_left
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoanLeft(Double loanLeft) {
        this.loanLeft = loanLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.plan_time
     *
     * @return the value of gjj_repay_plan_detail.plan_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getPlanTime() {
        return planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.plan_time
     *
     * @param planTime the value for gjj_repay_plan_detail.plan_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setPlanTime(Date planTime) {
        this.planTime = planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.remark
     *
     * @return the value of gjj_repay_plan_detail.remark
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.remark
     *
     * @param remark the value for gjj_repay_plan_detail.remark
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan_detail.parse_time
     *
     * @return the value of gjj_repay_plan_detail.parse_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan_detail.parse_time
     *
     * @param parseTime the value for gjj_repay_plan_detail.parse_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime(Date parseTime) {
        this.parseTime = parseTime;
    }
}