package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjRepayDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.Id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String userAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.loan_acc
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String loanAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.name
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.acc_no
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String accNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.loan_amount
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Double loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.loan_month
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Integer loanMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.type_code
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.loan_src
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String loanSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.loan_term
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Integer loanTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.trade_amount
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Double tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.loan_type
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String loanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.loan_teller
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private String loanTeller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.trade_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Date tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_detail.parse_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    private Date parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.Id
     *
     * @return the value of gjj_repay_detail.Id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.Id
     *
     * @param id the value for gjj_repay_detail.Id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.user_acc_id
     *
     * @return the value of gjj_repay_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getUserAccId() {
        return userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.user_acc_id
     *
     * @param userAccId the value for gjj_repay_detail.user_acc_id
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setUserAccId(String userAccId) {
        this.userAccId = userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.loan_acc
     *
     * @return the value of gjj_repay_detail.loan_acc
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getLoanAcc() {
        return loanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.loan_acc
     *
     * @param loanAcc the value for gjj_repay_detail.loan_acc
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLoanAcc(String loanAcc) {
        this.loanAcc = loanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.name
     *
     * @return the value of gjj_repay_detail.name
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.name
     *
     * @param name the value for gjj_repay_detail.name
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.acc_no
     *
     * @return the value of gjj_repay_detail.acc_no
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.acc_no
     *
     * @param accNo the value for gjj_repay_detail.acc_no
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setAccNo(String accNo) {
        this.accNo = accNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.loan_amount
     *
     * @return the value of gjj_repay_detail.loan_amount
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Double getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.loan_amount
     *
     * @param loanAmount the value for gjj_repay_detail.loan_amount
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLoanAmount(Double loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.loan_month
     *
     * @return the value of gjj_repay_detail.loan_month
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Integer getLoanMonth() {
        return loanMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.loan_month
     *
     * @param loanMonth the value for gjj_repay_detail.loan_month
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLoanMonth(Integer loanMonth) {
        this.loanMonth = loanMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.type_code
     *
     * @return the value of gjj_repay_detail.type_code
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.type_code
     *
     * @param typeCode the value for gjj_repay_detail.type_code
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.loan_src
     *
     * @return the value of gjj_repay_detail.loan_src
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getLoanSrc() {
        return loanSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.loan_src
     *
     * @param loanSrc the value for gjj_repay_detail.loan_src
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLoanSrc(String loanSrc) {
        this.loanSrc = loanSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.loan_term
     *
     * @return the value of gjj_repay_detail.loan_term
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Integer getLoanTerm() {
        return loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.loan_term
     *
     * @param loanTerm the value for gjj_repay_detail.loan_term
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLoanTerm(Integer loanTerm) {
        this.loanTerm = loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.trade_amount
     *
     * @return the value of gjj_repay_detail.trade_amount
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Double getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.trade_amount
     *
     * @param tradeAmount the value for gjj_repay_detail.trade_amount
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTradeAmount(Double tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.loan_type
     *
     * @return the value of gjj_repay_detail.loan_type
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getLoanType() {
        return loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.loan_type
     *
     * @param loanType the value for gjj_repay_detail.loan_type
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLoanType(String loanType) {
        this.loanType = loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.loan_teller
     *
     * @return the value of gjj_repay_detail.loan_teller
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getLoanTeller() {
        return loanTeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.loan_teller
     *
     * @param loanTeller the value for gjj_repay_detail.loan_teller
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setLoanTeller(String loanTeller) {
        this.loanTeller = loanTeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.trade_time
     *
     * @return the value of gjj_repay_detail.trade_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.trade_time
     *
     * @param tradeTime the value for gjj_repay_detail.trade_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_detail.parse_time
     *
     * @return the value of gjj_repay_detail.parse_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Date getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_detail.parse_time
     *
     * @param parseTime the value for gjj_repay_detail.parse_time
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setParseTime(Date parseTime) {
        this.parseTime = parseTime;
    }
}