package com.rlogin.domain.gjj;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GjjRepayPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public GjjRepayPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNull() {
            addCriterion("user_acc_id is null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNotNull() {
            addCriterion("user_acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdEqualTo(String value) {
            addCriterion("user_acc_id =", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotEqualTo(String value) {
            addCriterion("user_acc_id <>", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThan(String value) {
            addCriterion("user_acc_id >", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_acc_id >=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThan(String value) {
            addCriterion("user_acc_id <", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThanOrEqualTo(String value) {
            addCriterion("user_acc_id <=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLike(String value) {
            addCriterion("user_acc_id like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotLike(String value) {
            addCriterion("user_acc_id not like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIn(List<String> values) {
            addCriterion("user_acc_id in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotIn(List<String> values) {
            addCriterion("user_acc_id not in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdBetween(String value1, String value2) {
            addCriterion("user_acc_id between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotBetween(String value1, String value2) {
            addCriterion("user_acc_id not between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andLoanIdIsNull() {
            addCriterion("loan_id is null");
            return (Criteria) this;
        }

        public Criteria andLoanIdIsNotNull() {
            addCriterion("loan_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoanIdEqualTo(String value) {
            addCriterion("loan_id =", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdNotEqualTo(String value) {
            addCriterion("loan_id <>", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdGreaterThan(String value) {
            addCriterion("loan_id >", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdGreaterThanOrEqualTo(String value) {
            addCriterion("loan_id >=", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdLessThan(String value) {
            addCriterion("loan_id <", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdLessThanOrEqualTo(String value) {
            addCriterion("loan_id <=", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdLike(String value) {
            addCriterion("loan_id like", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdNotLike(String value) {
            addCriterion("loan_id not like", value, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdIn(List<String> values) {
            addCriterion("loan_id in", values, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdNotIn(List<String> values) {
            addCriterion("loan_id not in", values, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdBetween(String value1, String value2) {
            addCriterion("loan_id between", value1, value2, "loanId");
            return (Criteria) this;
        }

        public Criteria andLoanIdNotBetween(String value1, String value2) {
            addCriterion("loan_id not between", value1, value2, "loanId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAccIdIsNull() {
            addCriterion("acc_id is null");
            return (Criteria) this;
        }

        public Criteria andAccIdIsNotNull() {
            addCriterion("acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccIdEqualTo(String value) {
            addCriterion("acc_id =", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotEqualTo(String value) {
            addCriterion("acc_id <>", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdGreaterThan(String value) {
            addCriterion("acc_id >", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdGreaterThanOrEqualTo(String value) {
            addCriterion("acc_id >=", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLessThan(String value) {
            addCriterion("acc_id <", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLessThanOrEqualTo(String value) {
            addCriterion("acc_id <=", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLike(String value) {
            addCriterion("acc_id like", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotLike(String value) {
            addCriterion("acc_id not like", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdIn(List<String> values) {
            addCriterion("acc_id in", values, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotIn(List<String> values) {
            addCriterion("acc_id not in", values, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdBetween(String value1, String value2) {
            addCriterion("acc_id between", value1, value2, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotBetween(String value1, String value2) {
            addCriterion("acc_id not between", value1, value2, "accId");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineIsNull() {
            addCriterion("loan_deadline is null");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineIsNotNull() {
            addCriterion("loan_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineEqualTo(Date value) {
            addCriterionForJDBCDate("loan_deadline =", value, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineNotEqualTo(Date value) {
            addCriterionForJDBCDate("loan_deadline <>", value, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineGreaterThan(Date value) {
            addCriterionForJDBCDate("loan_deadline >", value, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("loan_deadline >=", value, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineLessThan(Date value) {
            addCriterionForJDBCDate("loan_deadline <", value, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("loan_deadline <=", value, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineIn(List<Date> values) {
            addCriterionForJDBCDate("loan_deadline in", values, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineNotIn(List<Date> values) {
            addCriterionForJDBCDate("loan_deadline not in", values, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("loan_deadline between", value1, value2, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanDeadlineNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("loan_deadline not between", value1, value2, "loanDeadline");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceIsNull() {
            addCriterion("loan_balance is null");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceIsNotNull() {
            addCriterion("loan_balance is not null");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceEqualTo(Double value) {
            addCriterion("loan_balance =", value, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceNotEqualTo(Double value) {
            addCriterion("loan_balance <>", value, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceGreaterThan(Double value) {
            addCriterion("loan_balance >", value, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceGreaterThanOrEqualTo(Double value) {
            addCriterion("loan_balance >=", value, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceLessThan(Double value) {
            addCriterion("loan_balance <", value, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceLessThanOrEqualTo(Double value) {
            addCriterion("loan_balance <=", value, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceIn(List<Double> values) {
            addCriterion("loan_balance in", values, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceNotIn(List<Double> values) {
            addCriterion("loan_balance not in", values, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceBetween(Double value1, Double value2) {
            addCriterion("loan_balance between", value1, value2, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanBalanceNotBetween(Double value1, Double value2) {
            addCriterion("loan_balance not between", value1, value2, "loanBalance");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNull() {
            addCriterion("loan_amount is null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNotNull() {
            addCriterion("loan_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountEqualTo(Double value) {
            addCriterion("loan_amount =", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotEqualTo(Double value) {
            addCriterion("loan_amount <>", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThan(Double value) {
            addCriterion("loan_amount >", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("loan_amount >=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThan(Double value) {
            addCriterion("loan_amount <", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThanOrEqualTo(Double value) {
            addCriterion("loan_amount <=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIn(List<Double> values) {
            addCriterion("loan_amount in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotIn(List<Double> values) {
            addCriterion("loan_amount not in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountBetween(Double value1, Double value2) {
            addCriterion("loan_amount between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotBetween(Double value1, Double value2) {
            addCriterion("loan_amount not between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountIsNull() {
            addCriterion("loan_term_amount is null");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountIsNotNull() {
            addCriterion("loan_term_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountEqualTo(Integer value) {
            addCriterion("loan_term_amount =", value, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountNotEqualTo(Integer value) {
            addCriterion("loan_term_amount <>", value, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountGreaterThan(Integer value) {
            addCriterion("loan_term_amount >", value, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_term_amount >=", value, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountLessThan(Integer value) {
            addCriterion("loan_term_amount <", value, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountLessThanOrEqualTo(Integer value) {
            addCriterion("loan_term_amount <=", value, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountIn(List<Integer> values) {
            addCriterion("loan_term_amount in", values, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountNotIn(List<Integer> values) {
            addCriterion("loan_term_amount not in", values, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountBetween(Integer value1, Integer value2) {
            addCriterion("loan_term_amount between", value1, value2, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_term_amount not between", value1, value2, "loanTermAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftIsNull() {
            addCriterion("loan_term_left is null");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftIsNotNull() {
            addCriterion("loan_term_left is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftEqualTo(Integer value) {
            addCriterion("loan_term_left =", value, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftNotEqualTo(Integer value) {
            addCriterion("loan_term_left <>", value, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftGreaterThan(Integer value) {
            addCriterion("loan_term_left >", value, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_term_left >=", value, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftLessThan(Integer value) {
            addCriterion("loan_term_left <", value, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftLessThanOrEqualTo(Integer value) {
            addCriterion("loan_term_left <=", value, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftIn(List<Integer> values) {
            addCriterion("loan_term_left in", values, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftNotIn(List<Integer> values) {
            addCriterion("loan_term_left not in", values, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftBetween(Integer value1, Integer value2) {
            addCriterion("loan_term_left between", value1, value2, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLoanTermLeftNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_term_left not between", value1, value2, "loanTermLeft");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeIsNull() {
            addCriterion("last_trade_time is null");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeIsNotNull() {
            addCriterion("last_trade_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeEqualTo(Date value) {
            addCriterionForJDBCDate("last_trade_time =", value, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("last_trade_time <>", value, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("last_trade_time >", value, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_trade_time >=", value, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeLessThan(Date value) {
            addCriterionForJDBCDate("last_trade_time <", value, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_trade_time <=", value, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeIn(List<Date> values) {
            addCriterionForJDBCDate("last_trade_time in", values, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("last_trade_time not in", values, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_trade_time between", value1, value2, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andLastTradeTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_trade_time not between", value1, value2, "lastTradeTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNull() {
            addCriterion("parse_time is null");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNotNull() {
            addCriterion("parse_time is not null");
            return (Criteria) this;
        }

        public Criteria andParseTimeEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time =", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time <>", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("parse_time >", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time >=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThan(Date value) {
            addCriterionForJDBCDate("parse_time <", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time <=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeIn(List<Date> values) {
            addCriterionForJDBCDate("parse_time in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("parse_time not in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("parse_time between", value1, value2, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("parse_time not between", value1, value2, "parseTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated do_not_delete_during_merge Sun May 17 11:53:26 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_repay_plan
     *
     * @mbggenerated Sun May 17 11:53:26 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}