package com.rlogin.domain.gjj;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GjjRepayDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public GjjRepayDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNull() {
            addCriterion("user_acc_id is null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIsNotNull() {
            addCriterion("user_acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccIdEqualTo(String value) {
            addCriterion("user_acc_id =", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotEqualTo(String value) {
            addCriterion("user_acc_id <>", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThan(String value) {
            addCriterion("user_acc_id >", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_acc_id >=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThan(String value) {
            addCriterion("user_acc_id <", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLessThanOrEqualTo(String value) {
            addCriterion("user_acc_id <=", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdLike(String value) {
            addCriterion("user_acc_id like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotLike(String value) {
            addCriterion("user_acc_id not like", value, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdIn(List<String> values) {
            addCriterion("user_acc_id in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotIn(List<String> values) {
            addCriterion("user_acc_id not in", values, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdBetween(String value1, String value2) {
            addCriterion("user_acc_id between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andUserAccIdNotBetween(String value1, String value2) {
            addCriterion("user_acc_id not between", value1, value2, "userAccId");
            return (Criteria) this;
        }

        public Criteria andLoanAccIsNull() {
            addCriterion("loan_acc is null");
            return (Criteria) this;
        }

        public Criteria andLoanAccIsNotNull() {
            addCriterion("loan_acc is not null");
            return (Criteria) this;
        }

        public Criteria andLoanAccEqualTo(String value) {
            addCriterion("loan_acc =", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotEqualTo(String value) {
            addCriterion("loan_acc <>", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccGreaterThan(String value) {
            addCriterion("loan_acc >", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccGreaterThanOrEqualTo(String value) {
            addCriterion("loan_acc >=", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccLessThan(String value) {
            addCriterion("loan_acc <", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccLessThanOrEqualTo(String value) {
            addCriterion("loan_acc <=", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccLike(String value) {
            addCriterion("loan_acc like", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotLike(String value) {
            addCriterion("loan_acc not like", value, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccIn(List<String> values) {
            addCriterion("loan_acc in", values, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotIn(List<String> values) {
            addCriterion("loan_acc not in", values, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccBetween(String value1, String value2) {
            addCriterion("loan_acc between", value1, value2, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andLoanAccNotBetween(String value1, String value2) {
            addCriterion("loan_acc not between", value1, value2, "loanAcc");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAccNoIsNull() {
            addCriterion("acc_no is null");
            return (Criteria) this;
        }

        public Criteria andAccNoIsNotNull() {
            addCriterion("acc_no is not null");
            return (Criteria) this;
        }

        public Criteria andAccNoEqualTo(String value) {
            addCriterion("acc_no =", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoNotEqualTo(String value) {
            addCriterion("acc_no <>", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoGreaterThan(String value) {
            addCriterion("acc_no >", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoGreaterThanOrEqualTo(String value) {
            addCriterion("acc_no >=", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoLessThan(String value) {
            addCriterion("acc_no <", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoLessThanOrEqualTo(String value) {
            addCriterion("acc_no <=", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoLike(String value) {
            addCriterion("acc_no like", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoNotLike(String value) {
            addCriterion("acc_no not like", value, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoIn(List<String> values) {
            addCriterion("acc_no in", values, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoNotIn(List<String> values) {
            addCriterion("acc_no not in", values, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoBetween(String value1, String value2) {
            addCriterion("acc_no between", value1, value2, "accNo");
            return (Criteria) this;
        }

        public Criteria andAccNoNotBetween(String value1, String value2) {
            addCriterion("acc_no not between", value1, value2, "accNo");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNull() {
            addCriterion("loan_amount is null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIsNotNull() {
            addCriterion("loan_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLoanAmountEqualTo(Double value) {
            addCriterion("loan_amount =", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotEqualTo(Double value) {
            addCriterion("loan_amount <>", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThan(Double value) {
            addCriterion("loan_amount >", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("loan_amount >=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThan(Double value) {
            addCriterion("loan_amount <", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountLessThanOrEqualTo(Double value) {
            addCriterion("loan_amount <=", value, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountIn(List<Double> values) {
            addCriterion("loan_amount in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotIn(List<Double> values) {
            addCriterion("loan_amount not in", values, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountBetween(Double value1, Double value2) {
            addCriterion("loan_amount between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanAmountNotBetween(Double value1, Double value2) {
            addCriterion("loan_amount not between", value1, value2, "loanAmount");
            return (Criteria) this;
        }

        public Criteria andLoanMonthIsNull() {
            addCriterion("loan_month is null");
            return (Criteria) this;
        }

        public Criteria andLoanMonthIsNotNull() {
            addCriterion("loan_month is not null");
            return (Criteria) this;
        }

        public Criteria andLoanMonthEqualTo(Integer value) {
            addCriterion("loan_month =", value, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthNotEqualTo(Integer value) {
            addCriterion("loan_month <>", value, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthGreaterThan(Integer value) {
            addCriterion("loan_month >", value, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_month >=", value, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthLessThan(Integer value) {
            addCriterion("loan_month <", value, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthLessThanOrEqualTo(Integer value) {
            addCriterion("loan_month <=", value, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthIn(List<Integer> values) {
            addCriterion("loan_month in", values, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthNotIn(List<Integer> values) {
            addCriterion("loan_month not in", values, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthBetween(Integer value1, Integer value2) {
            addCriterion("loan_month between", value1, value2, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andLoanMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_month not between", value1, value2, "loanMonth");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIsNull() {
            addCriterion("type_code is null");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIsNotNull() {
            addCriterion("type_code is not null");
            return (Criteria) this;
        }

        public Criteria andTypeCodeEqualTo(String value) {
            addCriterion("type_code =", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotEqualTo(String value) {
            addCriterion("type_code <>", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeGreaterThan(String value) {
            addCriterion("type_code >", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("type_code >=", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLessThan(String value) {
            addCriterion("type_code <", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("type_code <=", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeLike(String value) {
            addCriterion("type_code like", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotLike(String value) {
            addCriterion("type_code not like", value, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeIn(List<String> values) {
            addCriterion("type_code in", values, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotIn(List<String> values) {
            addCriterion("type_code not in", values, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeBetween(String value1, String value2) {
            addCriterion("type_code between", value1, value2, "typeCode");
            return (Criteria) this;
        }

        public Criteria andTypeCodeNotBetween(String value1, String value2) {
            addCriterion("type_code not between", value1, value2, "typeCode");
            return (Criteria) this;
        }

        public Criteria andLoanSrcIsNull() {
            addCriterion("loan_src is null");
            return (Criteria) this;
        }

        public Criteria andLoanSrcIsNotNull() {
            addCriterion("loan_src is not null");
            return (Criteria) this;
        }

        public Criteria andLoanSrcEqualTo(String value) {
            addCriterion("loan_src =", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcNotEqualTo(String value) {
            addCriterion("loan_src <>", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcGreaterThan(String value) {
            addCriterion("loan_src >", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcGreaterThanOrEqualTo(String value) {
            addCriterion("loan_src >=", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcLessThan(String value) {
            addCriterion("loan_src <", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcLessThanOrEqualTo(String value) {
            addCriterion("loan_src <=", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcLike(String value) {
            addCriterion("loan_src like", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcNotLike(String value) {
            addCriterion("loan_src not like", value, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcIn(List<String> values) {
            addCriterion("loan_src in", values, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcNotIn(List<String> values) {
            addCriterion("loan_src not in", values, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcBetween(String value1, String value2) {
            addCriterion("loan_src between", value1, value2, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanSrcNotBetween(String value1, String value2) {
            addCriterion("loan_src not between", value1, value2, "loanSrc");
            return (Criteria) this;
        }

        public Criteria andLoanTermIsNull() {
            addCriterion("loan_term is null");
            return (Criteria) this;
        }

        public Criteria andLoanTermIsNotNull() {
            addCriterion("loan_term is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTermEqualTo(Integer value) {
            addCriterion("loan_term =", value, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermNotEqualTo(Integer value) {
            addCriterion("loan_term <>", value, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermGreaterThan(Integer value) {
            addCriterion("loan_term >", value, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_term >=", value, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermLessThan(Integer value) {
            addCriterion("loan_term <", value, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermLessThanOrEqualTo(Integer value) {
            addCriterion("loan_term <=", value, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermIn(List<Integer> values) {
            addCriterion("loan_term in", values, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermNotIn(List<Integer> values) {
            addCriterion("loan_term not in", values, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermBetween(Integer value1, Integer value2) {
            addCriterion("loan_term between", value1, value2, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andLoanTermNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_term not between", value1, value2, "loanTerm");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIsNull() {
            addCriterion("trade_amount is null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIsNotNull() {
            addCriterion("trade_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountEqualTo(Double value) {
            addCriterion("trade_amount =", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotEqualTo(Double value) {
            addCriterion("trade_amount <>", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountGreaterThan(Double value) {
            addCriterion("trade_amount >", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("trade_amount >=", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLessThan(Double value) {
            addCriterion("trade_amount <", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLessThanOrEqualTo(Double value) {
            addCriterion("trade_amount <=", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIn(List<Double> values) {
            addCriterion("trade_amount in", values, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotIn(List<Double> values) {
            addCriterion("trade_amount not in", values, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountBetween(Double value1, Double value2) {
            addCriterion("trade_amount between", value1, value2, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotBetween(Double value1, Double value2) {
            addCriterion("trade_amount not between", value1, value2, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIsNull() {
            addCriterion("loan_type is null");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIsNotNull() {
            addCriterion("loan_type is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTypeEqualTo(String value) {
            addCriterion("loan_type =", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotEqualTo(String value) {
            addCriterion("loan_type <>", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeGreaterThan(String value) {
            addCriterion("loan_type >", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeGreaterThanOrEqualTo(String value) {
            addCriterion("loan_type >=", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLessThan(String value) {
            addCriterion("loan_type <", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLessThanOrEqualTo(String value) {
            addCriterion("loan_type <=", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLike(String value) {
            addCriterion("loan_type like", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotLike(String value) {
            addCriterion("loan_type not like", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIn(List<String> values) {
            addCriterion("loan_type in", values, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotIn(List<String> values) {
            addCriterion("loan_type not in", values, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeBetween(String value1, String value2) {
            addCriterion("loan_type between", value1, value2, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotBetween(String value1, String value2) {
            addCriterion("loan_type not between", value1, value2, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTellerIsNull() {
            addCriterion("loan_teller is null");
            return (Criteria) this;
        }

        public Criteria andLoanTellerIsNotNull() {
            addCriterion("loan_teller is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTellerEqualTo(String value) {
            addCriterion("loan_teller =", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerNotEqualTo(String value) {
            addCriterion("loan_teller <>", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerGreaterThan(String value) {
            addCriterion("loan_teller >", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerGreaterThanOrEqualTo(String value) {
            addCriterion("loan_teller >=", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerLessThan(String value) {
            addCriterion("loan_teller <", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerLessThanOrEqualTo(String value) {
            addCriterion("loan_teller <=", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerLike(String value) {
            addCriterion("loan_teller like", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerNotLike(String value) {
            addCriterion("loan_teller not like", value, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerIn(List<String> values) {
            addCriterion("loan_teller in", values, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerNotIn(List<String> values) {
            addCriterion("loan_teller not in", values, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerBetween(String value1, String value2) {
            addCriterion("loan_teller between", value1, value2, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andLoanTellerNotBetween(String value1, String value2) {
            addCriterion("loan_teller not between", value1, value2, "loanTeller");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNull() {
            addCriterion("trade_time is null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNotNull() {
            addCriterion("trade_time is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeEqualTo(Date value) {
            addCriterionForJDBCDate("trade_time =", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("trade_time <>", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("trade_time >", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("trade_time >=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThan(Date value) {
            addCriterionForJDBCDate("trade_time <", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("trade_time <=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIn(List<Date> values) {
            addCriterionForJDBCDate("trade_time in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("trade_time not in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("trade_time between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("trade_time not between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNull() {
            addCriterion("parse_time is null");
            return (Criteria) this;
        }

        public Criteria andParseTimeIsNotNull() {
            addCriterion("parse_time is not null");
            return (Criteria) this;
        }

        public Criteria andParseTimeEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time =", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time <>", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("parse_time >", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time >=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThan(Date value) {
            addCriterionForJDBCDate("parse_time <", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("parse_time <=", value, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeIn(List<Date> values) {
            addCriterionForJDBCDate("parse_time in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("parse_time not in", values, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("parse_time between", value1, value2, "parseTime");
            return (Criteria) this;
        }

        public Criteria andParseTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("parse_time not between", value1, value2, "parseTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated do_not_delete_during_merge Fri May 22 14:26:26 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_repay_detail
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}