package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.acc_id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private String accId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.acc_pwd
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private String accPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.name
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.id_card
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.gjj_acc
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private String gjjAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.balance
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.gjj_rate
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double gjjRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.m_contribute
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Double mContribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.acc_status
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Integer accStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.login_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.parse_time1
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.parse_time2
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.parse_time3
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.parse_time4
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.parse_time5
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.parse_time6
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_user.parse_time7
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    private Date parseTime7;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.id
     *
     * @return the value of gjj_user.id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.id
     *
     * @param id the value for gjj_user.id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.acc_id
     *
     * @return the value of gjj_user.acc_id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.acc_id
     *
     * @param accId the value for gjj_user.acc_id
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setAccId(String accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.acc_pwd
     *
     * @return the value of gjj_user.acc_pwd
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getAccPwd() {
        return accPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.acc_pwd
     *
     * @param accPwd the value for gjj_user.acc_pwd
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setAccPwd(String accPwd) {
        this.accPwd = accPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.name
     *
     * @return the value of gjj_user.name
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.name
     *
     * @param name the value for gjj_user.name
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.id_card
     *
     * @return the value of gjj_user.id_card
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.id_card
     *
     * @param idCard the value for gjj_user.id_card
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.gjj_acc
     *
     * @return the value of gjj_user.gjj_acc
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public String getGjjAcc() {
        return gjjAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.gjj_acc
     *
     * @param gjjAcc the value for gjj_user.gjj_acc
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setGjjAcc(String gjjAcc) {
        this.gjjAcc = gjjAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.balance
     *
     * @return the value of gjj_user.balance
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.balance
     *
     * @param balance the value for gjj_user.balance
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.gjj_rate
     *
     * @return the value of gjj_user.gjj_rate
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getGjjRate() {
        return gjjRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.gjj_rate
     *
     * @param gjjRate the value for gjj_user.gjj_rate
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setGjjRate(Double gjjRate) {
        this.gjjRate = gjjRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.m_contribute
     *
     * @return the value of gjj_user.m_contribute
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Double getmContribute() {
        return mContribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.m_contribute
     *
     * @param mContribute the value for gjj_user.m_contribute
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setmContribute(Double mContribute) {
        this.mContribute = mContribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.acc_status
     *
     * @return the value of gjj_user.acc_status
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Integer getAccStatus() {
        return accStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.acc_status
     *
     * @param accStatus the value for gjj_user.acc_status
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setAccStatus(Integer accStatus) {
        this.accStatus = accStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.login_time
     *
     * @return the value of gjj_user.login_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.login_time
     *
     * @param loginTime the value for gjj_user.login_time
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.parse_time1
     *
     * @return the value of gjj_user.parse_time1
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime1() {
        return parseTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.parse_time1
     *
     * @param parseTime1 the value for gjj_user.parse_time1
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime1(Date parseTime1) {
        this.parseTime1 = parseTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.parse_time2
     *
     * @return the value of gjj_user.parse_time2
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime2() {
        return parseTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.parse_time2
     *
     * @param parseTime2 the value for gjj_user.parse_time2
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime2(Date parseTime2) {
        this.parseTime2 = parseTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.parse_time3
     *
     * @return the value of gjj_user.parse_time3
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime3() {
        return parseTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.parse_time3
     *
     * @param parseTime3 the value for gjj_user.parse_time3
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime3(Date parseTime3) {
        this.parseTime3 = parseTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.parse_time4
     *
     * @return the value of gjj_user.parse_time4
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime4() {
        return parseTime4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.parse_time4
     *
     * @param parseTime4 the value for gjj_user.parse_time4
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime4(Date parseTime4) {
        this.parseTime4 = parseTime4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.parse_time5
     *
     * @return the value of gjj_user.parse_time5
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime5() {
        return parseTime5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.parse_time5
     *
     * @param parseTime5 the value for gjj_user.parse_time5
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime5(Date parseTime5) {
        this.parseTime5 = parseTime5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.parse_time6
     *
     * @return the value of gjj_user.parse_time6
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime6() {
        return parseTime6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.parse_time6
     *
     * @param parseTime6 the value for gjj_user.parse_time6
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime6(Date parseTime6) {
        this.parseTime6 = parseTime6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_user.parse_time7
     *
     * @return the value of gjj_user.parse_time7
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public Date getParseTime7() {
        return parseTime7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_user.parse_time7
     *
     * @param parseTime7 the value for gjj_user.parse_time7
     *
     * @mbggenerated Fri May 22 14:26:26 CST 2015
     */
    public void setParseTime7(Date parseTime7) {
        this.parseTime7 = parseTime7;
    }
}