package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjLoanStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.Id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.user_acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String userAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.name
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.id_care_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String idCareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.id_card
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.loan_acc
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String loanAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.loan_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Double loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.loan_months
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Integer loanMonths;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.loan_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String loanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.house_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.bank
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.loan_status
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String loanStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_loan_status.parse_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Date parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.Id
     *
     * @return the value of gjj_loan_status.Id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.Id
     *
     * @param id the value for gjj_loan_status.Id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.user_acc_id
     *
     * @return the value of gjj_loan_status.user_acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getUserAccId() {
        return userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.user_acc_id
     *
     * @param userAccId the value for gjj_loan_status.user_acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setUserAccId(String userAccId) {
        this.userAccId = userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.name
     *
     * @return the value of gjj_loan_status.name
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.name
     *
     * @param name the value for gjj_loan_status.name
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.id_care_type
     *
     * @return the value of gjj_loan_status.id_care_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getIdCareType() {
        return idCareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.id_care_type
     *
     * @param idCareType the value for gjj_loan_status.id_care_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setIdCareType(String idCareType) {
        this.idCareType = idCareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.id_card
     *
     * @return the value of gjj_loan_status.id_card
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.id_card
     *
     * @param idCard the value for gjj_loan_status.id_card
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.loan_acc
     *
     * @return the value of gjj_loan_status.loan_acc
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getLoanAcc() {
        return loanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.loan_acc
     *
     * @param loanAcc the value for gjj_loan_status.loan_acc
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanAcc(String loanAcc) {
        this.loanAcc = loanAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.loan_amount
     *
     * @return the value of gjj_loan_status.loan_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Double getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.loan_amount
     *
     * @param loanAmount the value for gjj_loan_status.loan_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanAmount(Double loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.loan_months
     *
     * @return the value of gjj_loan_status.loan_months
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Integer getLoanMonths() {
        return loanMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.loan_months
     *
     * @param loanMonths the value for gjj_loan_status.loan_months
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanMonths(Integer loanMonths) {
        this.loanMonths = loanMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.loan_type
     *
     * @return the value of gjj_loan_status.loan_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getLoanType() {
        return loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.loan_type
     *
     * @param loanType the value for gjj_loan_status.loan_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanType(String loanType) {
        this.loanType = loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.house_type
     *
     * @return the value of gjj_loan_status.house_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.house_type
     *
     * @param houseType the value for gjj_loan_status.house_type
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.bank
     *
     * @return the value of gjj_loan_status.bank
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.bank
     *
     * @param bank the value for gjj_loan_status.bank
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.loan_status
     *
     * @return the value of gjj_loan_status.loan_status
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getLoanStatus() {
        return loanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.loan_status
     *
     * @param loanStatus the value for gjj_loan_status.loan_status
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanStatus(String loanStatus) {
        this.loanStatus = loanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_loan_status.parse_time
     *
     * @return the value of gjj_loan_status.parse_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Date getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_loan_status.parse_time
     *
     * @param parseTime the value for gjj_loan_status.parse_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setParseTime(Date parseTime) {
        this.parseTime = parseTime;
    }
}