package com.rlogin.domain.gjj;

import java.util.Date;

public class GjjRepayPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.Id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.user_acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String userAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.loan_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.name
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private String accId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.loan_deadline
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Date loanDeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.loan_balance
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Double loanBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.loan_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Double loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.loan_term_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Integer loanTermAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.loan_term_left
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Integer loanTermLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.last_trade_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Date lastTradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gjj_repay_plan.parse_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    private Date parseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.Id
     *
     * @return the value of gjj_repay_plan.Id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.Id
     *
     * @param id the value for gjj_repay_plan.Id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.user_acc_id
     *
     * @return the value of gjj_repay_plan.user_acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getUserAccId() {
        return userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.user_acc_id
     *
     * @param userAccId the value for gjj_repay_plan.user_acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setUserAccId(String userAccId) {
        this.userAccId = userAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.loan_id
     *
     * @return the value of gjj_repay_plan.loan_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.loan_id
     *
     * @param loanId the value for gjj_repay_plan.loan_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.name
     *
     * @return the value of gjj_repay_plan.name
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.name
     *
     * @param name the value for gjj_repay_plan.name
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.acc_id
     *
     * @return the value of gjj_repay_plan.acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.acc_id
     *
     * @param accId the value for gjj_repay_plan.acc_id
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setAccId(String accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.loan_deadline
     *
     * @return the value of gjj_repay_plan.loan_deadline
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Date getLoanDeadline() {
        return loanDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.loan_deadline
     *
     * @param loanDeadline the value for gjj_repay_plan.loan_deadline
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanDeadline(Date loanDeadline) {
        this.loanDeadline = loanDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.loan_balance
     *
     * @return the value of gjj_repay_plan.loan_balance
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Double getLoanBalance() {
        return loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.loan_balance
     *
     * @param loanBalance the value for gjj_repay_plan.loan_balance
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanBalance(Double loanBalance) {
        this.loanBalance = loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.loan_amount
     *
     * @return the value of gjj_repay_plan.loan_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Double getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.loan_amount
     *
     * @param loanAmount the value for gjj_repay_plan.loan_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanAmount(Double loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.loan_term_amount
     *
     * @return the value of gjj_repay_plan.loan_term_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Integer getLoanTermAmount() {
        return loanTermAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.loan_term_amount
     *
     * @param loanTermAmount the value for gjj_repay_plan.loan_term_amount
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanTermAmount(Integer loanTermAmount) {
        this.loanTermAmount = loanTermAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.loan_term_left
     *
     * @return the value of gjj_repay_plan.loan_term_left
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Integer getLoanTermLeft() {
        return loanTermLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.loan_term_left
     *
     * @param loanTermLeft the value for gjj_repay_plan.loan_term_left
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLoanTermLeft(Integer loanTermLeft) {
        this.loanTermLeft = loanTermLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.last_trade_time
     *
     * @return the value of gjj_repay_plan.last_trade_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Date getLastTradeTime() {
        return lastTradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.last_trade_time
     *
     * @param lastTradeTime the value for gjj_repay_plan.last_trade_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setLastTradeTime(Date lastTradeTime) {
        this.lastTradeTime = lastTradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gjj_repay_plan.parse_time
     *
     * @return the value of gjj_repay_plan.parse_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Date getParseTime() {
        return parseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gjj_repay_plan.parse_time
     *
     * @param parseTime the value for gjj_repay_plan.parse_time
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setParseTime(Date parseTime) {
        this.parseTime = parseTime;
    }
}