package com.rlogin.domain.gjj;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GjjUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public GjjUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccIdIsNull() {
            addCriterion("acc_id is null");
            return (Criteria) this;
        }

        public Criteria andAccIdIsNotNull() {
            addCriterion("acc_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccIdEqualTo(String value) {
            addCriterion("acc_id =", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotEqualTo(String value) {
            addCriterion("acc_id <>", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdGreaterThan(String value) {
            addCriterion("acc_id >", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdGreaterThanOrEqualTo(String value) {
            addCriterion("acc_id >=", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLessThan(String value) {
            addCriterion("acc_id <", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLessThanOrEqualTo(String value) {
            addCriterion("acc_id <=", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdLike(String value) {
            addCriterion("acc_id like", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotLike(String value) {
            addCriterion("acc_id not like", value, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdIn(List<String> values) {
            addCriterion("acc_id in", values, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotIn(List<String> values) {
            addCriterion("acc_id not in", values, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdBetween(String value1, String value2) {
            addCriterion("acc_id between", value1, value2, "accId");
            return (Criteria) this;
        }

        public Criteria andAccIdNotBetween(String value1, String value2) {
            addCriterion("acc_id not between", value1, value2, "accId");
            return (Criteria) this;
        }

        public Criteria andAccPwdIsNull() {
            addCriterion("acc_pwd is null");
            return (Criteria) this;
        }

        public Criteria andAccPwdIsNotNull() {
            addCriterion("acc_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andAccPwdEqualTo(String value) {
            addCriterion("acc_pwd =", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdNotEqualTo(String value) {
            addCriterion("acc_pwd <>", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdGreaterThan(String value) {
            addCriterion("acc_pwd >", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdGreaterThanOrEqualTo(String value) {
            addCriterion("acc_pwd >=", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdLessThan(String value) {
            addCriterion("acc_pwd <", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdLessThanOrEqualTo(String value) {
            addCriterion("acc_pwd <=", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdLike(String value) {
            addCriterion("acc_pwd like", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdNotLike(String value) {
            addCriterion("acc_pwd not like", value, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdIn(List<String> values) {
            addCriterion("acc_pwd in", values, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdNotIn(List<String> values) {
            addCriterion("acc_pwd not in", values, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdBetween(String value1, String value2) {
            addCriterion("acc_pwd between", value1, value2, "accPwd");
            return (Criteria) this;
        }

        public Criteria andAccPwdNotBetween(String value1, String value2) {
            addCriterion("acc_pwd not between", value1, value2, "accPwd");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andGjjAccIsNull() {
            addCriterion("gjj_acc is null");
            return (Criteria) this;
        }

        public Criteria andGjjAccIsNotNull() {
            addCriterion("gjj_acc is not null");
            return (Criteria) this;
        }

        public Criteria andGjjAccEqualTo(String value) {
            addCriterion("gjj_acc =", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccNotEqualTo(String value) {
            addCriterion("gjj_acc <>", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccGreaterThan(String value) {
            addCriterion("gjj_acc >", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccGreaterThanOrEqualTo(String value) {
            addCriterion("gjj_acc >=", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccLessThan(String value) {
            addCriterion("gjj_acc <", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccLessThanOrEqualTo(String value) {
            addCriterion("gjj_acc <=", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccLike(String value) {
            addCriterion("gjj_acc like", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccNotLike(String value) {
            addCriterion("gjj_acc not like", value, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccIn(List<String> values) {
            addCriterion("gjj_acc in", values, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccNotIn(List<String> values) {
            addCriterion("gjj_acc not in", values, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccBetween(String value1, String value2) {
            addCriterion("gjj_acc between", value1, value2, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andGjjAccNotBetween(String value1, String value2) {
            addCriterion("gjj_acc not between", value1, value2, "gjjAcc");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(Double value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(Double value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(Double value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(Double value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(Double value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(Double value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<Double> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<Double> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(Double value1, Double value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(Double value1, Double value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andGjjRateIsNull() {
            addCriterion("gjj_rate is null");
            return (Criteria) this;
        }

        public Criteria andGjjRateIsNotNull() {
            addCriterion("gjj_rate is not null");
            return (Criteria) this;
        }

        public Criteria andGjjRateEqualTo(Double value) {
            addCriterion("gjj_rate =", value, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateNotEqualTo(Double value) {
            addCriterion("gjj_rate <>", value, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateGreaterThan(Double value) {
            addCriterion("gjj_rate >", value, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateGreaterThanOrEqualTo(Double value) {
            addCriterion("gjj_rate >=", value, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateLessThan(Double value) {
            addCriterion("gjj_rate <", value, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateLessThanOrEqualTo(Double value) {
            addCriterion("gjj_rate <=", value, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateIn(List<Double> values) {
            addCriterion("gjj_rate in", values, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateNotIn(List<Double> values) {
            addCriterion("gjj_rate not in", values, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateBetween(Double value1, Double value2) {
            addCriterion("gjj_rate between", value1, value2, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andGjjRateNotBetween(Double value1, Double value2) {
            addCriterion("gjj_rate not between", value1, value2, "gjjRate");
            return (Criteria) this;
        }

        public Criteria andMContributeIsNull() {
            addCriterion("m_contribute is null");
            return (Criteria) this;
        }

        public Criteria andMContributeIsNotNull() {
            addCriterion("m_contribute is not null");
            return (Criteria) this;
        }

        public Criteria andMContributeEqualTo(Double value) {
            addCriterion("m_contribute =", value, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeNotEqualTo(Double value) {
            addCriterion("m_contribute <>", value, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeGreaterThan(Double value) {
            addCriterion("m_contribute >", value, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeGreaterThanOrEqualTo(Double value) {
            addCriterion("m_contribute >=", value, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeLessThan(Double value) {
            addCriterion("m_contribute <", value, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeLessThanOrEqualTo(Double value) {
            addCriterion("m_contribute <=", value, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeIn(List<Double> values) {
            addCriterion("m_contribute in", values, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeNotIn(List<Double> values) {
            addCriterion("m_contribute not in", values, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeBetween(Double value1, Double value2) {
            addCriterion("m_contribute between", value1, value2, "mContribute");
            return (Criteria) this;
        }

        public Criteria andMContributeNotBetween(Double value1, Double value2) {
            addCriterion("m_contribute not between", value1, value2, "mContribute");
            return (Criteria) this;
        }

        public Criteria andAccStatusIsNull() {
            addCriterion("acc_status is null");
            return (Criteria) this;
        }

        public Criteria andAccStatusIsNotNull() {
            addCriterion("acc_status is not null");
            return (Criteria) this;
        }

        public Criteria andAccStatusEqualTo(Integer value) {
            addCriterion("acc_status =", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusNotEqualTo(Integer value) {
            addCriterion("acc_status <>", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusGreaterThan(Integer value) {
            addCriterion("acc_status >", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("acc_status >=", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusLessThan(Integer value) {
            addCriterion("acc_status <", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusLessThanOrEqualTo(Integer value) {
            addCriterion("acc_status <=", value, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusIn(List<Integer> values) {
            addCriterion("acc_status in", values, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusNotIn(List<Integer> values) {
            addCriterion("acc_status not in", values, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusBetween(Integer value1, Integer value2) {
            addCriterion("acc_status between", value1, value2, "accStatus");
            return (Criteria) this;
        }

        public Criteria andAccStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("acc_status not between", value1, value2, "accStatus");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNull() {
            addCriterion("login_time is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNotNull() {
            addCriterion("login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeEqualTo(Date value) {
            addCriterion("login_time =", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotEqualTo(Date value) {
            addCriterion("login_time <>", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThan(Date value) {
            addCriterion("login_time >", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("login_time >=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThan(Date value) {
            addCriterion("login_time <", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("login_time <=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIn(List<Date> values) {
            addCriterion("login_time in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotIn(List<Date> values) {
            addCriterion("login_time not in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeBetween(Date value1, Date value2) {
            addCriterion("login_time between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("login_time not between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andParseTime1IsNull() {
            addCriterion("parse_time1 is null");
            return (Criteria) this;
        }

        public Criteria andParseTime1IsNotNull() {
            addCriterion("parse_time1 is not null");
            return (Criteria) this;
        }

        public Criteria andParseTime1EqualTo(Date value) {
            addCriterion("parse_time1 =", value, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1NotEqualTo(Date value) {
            addCriterion("parse_time1 <>", value, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1GreaterThan(Date value) {
            addCriterion("parse_time1 >", value, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1GreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time1 >=", value, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1LessThan(Date value) {
            addCriterion("parse_time1 <", value, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1LessThanOrEqualTo(Date value) {
            addCriterion("parse_time1 <=", value, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1In(List<Date> values) {
            addCriterion("parse_time1 in", values, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1NotIn(List<Date> values) {
            addCriterion("parse_time1 not in", values, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1Between(Date value1, Date value2) {
            addCriterion("parse_time1 between", value1, value2, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime1NotBetween(Date value1, Date value2) {
            addCriterion("parse_time1 not between", value1, value2, "parseTime1");
            return (Criteria) this;
        }

        public Criteria andParseTime2IsNull() {
            addCriterion("parse_time2 is null");
            return (Criteria) this;
        }

        public Criteria andParseTime2IsNotNull() {
            addCriterion("parse_time2 is not null");
            return (Criteria) this;
        }

        public Criteria andParseTime2EqualTo(Date value) {
            addCriterion("parse_time2 =", value, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2NotEqualTo(Date value) {
            addCriterion("parse_time2 <>", value, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2GreaterThan(Date value) {
            addCriterion("parse_time2 >", value, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2GreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time2 >=", value, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2LessThan(Date value) {
            addCriterion("parse_time2 <", value, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2LessThanOrEqualTo(Date value) {
            addCriterion("parse_time2 <=", value, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2In(List<Date> values) {
            addCriterion("parse_time2 in", values, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2NotIn(List<Date> values) {
            addCriterion("parse_time2 not in", values, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2Between(Date value1, Date value2) {
            addCriterion("parse_time2 between", value1, value2, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime2NotBetween(Date value1, Date value2) {
            addCriterion("parse_time2 not between", value1, value2, "parseTime2");
            return (Criteria) this;
        }

        public Criteria andParseTime3IsNull() {
            addCriterion("parse_time3 is null");
            return (Criteria) this;
        }

        public Criteria andParseTime3IsNotNull() {
            addCriterion("parse_time3 is not null");
            return (Criteria) this;
        }

        public Criteria andParseTime3EqualTo(Date value) {
            addCriterion("parse_time3 =", value, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3NotEqualTo(Date value) {
            addCriterion("parse_time3 <>", value, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3GreaterThan(Date value) {
            addCriterion("parse_time3 >", value, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3GreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time3 >=", value, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3LessThan(Date value) {
            addCriterion("parse_time3 <", value, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3LessThanOrEqualTo(Date value) {
            addCriterion("parse_time3 <=", value, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3In(List<Date> values) {
            addCriterion("parse_time3 in", values, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3NotIn(List<Date> values) {
            addCriterion("parse_time3 not in", values, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3Between(Date value1, Date value2) {
            addCriterion("parse_time3 between", value1, value2, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime3NotBetween(Date value1, Date value2) {
            addCriterion("parse_time3 not between", value1, value2, "parseTime3");
            return (Criteria) this;
        }

        public Criteria andParseTime4IsNull() {
            addCriterion("parse_time4 is null");
            return (Criteria) this;
        }

        public Criteria andParseTime4IsNotNull() {
            addCriterion("parse_time4 is not null");
            return (Criteria) this;
        }

        public Criteria andParseTime4EqualTo(Date value) {
            addCriterion("parse_time4 =", value, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4NotEqualTo(Date value) {
            addCriterion("parse_time4 <>", value, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4GreaterThan(Date value) {
            addCriterion("parse_time4 >", value, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4GreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time4 >=", value, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4LessThan(Date value) {
            addCriterion("parse_time4 <", value, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4LessThanOrEqualTo(Date value) {
            addCriterion("parse_time4 <=", value, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4In(List<Date> values) {
            addCriterion("parse_time4 in", values, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4NotIn(List<Date> values) {
            addCriterion("parse_time4 not in", values, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4Between(Date value1, Date value2) {
            addCriterion("parse_time4 between", value1, value2, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime4NotBetween(Date value1, Date value2) {
            addCriterion("parse_time4 not between", value1, value2, "parseTime4");
            return (Criteria) this;
        }

        public Criteria andParseTime5IsNull() {
            addCriterion("parse_time5 is null");
            return (Criteria) this;
        }

        public Criteria andParseTime5IsNotNull() {
            addCriterion("parse_time5 is not null");
            return (Criteria) this;
        }

        public Criteria andParseTime5EqualTo(Date value) {
            addCriterion("parse_time5 =", value, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5NotEqualTo(Date value) {
            addCriterion("parse_time5 <>", value, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5GreaterThan(Date value) {
            addCriterion("parse_time5 >", value, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5GreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time5 >=", value, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5LessThan(Date value) {
            addCriterion("parse_time5 <", value, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5LessThanOrEqualTo(Date value) {
            addCriterion("parse_time5 <=", value, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5In(List<Date> values) {
            addCriterion("parse_time5 in", values, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5NotIn(List<Date> values) {
            addCriterion("parse_time5 not in", values, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5Between(Date value1, Date value2) {
            addCriterion("parse_time5 between", value1, value2, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime5NotBetween(Date value1, Date value2) {
            addCriterion("parse_time5 not between", value1, value2, "parseTime5");
            return (Criteria) this;
        }

        public Criteria andParseTime6IsNull() {
            addCriterion("parse_time6 is null");
            return (Criteria) this;
        }

        public Criteria andParseTime6IsNotNull() {
            addCriterion("parse_time6 is not null");
            return (Criteria) this;
        }

        public Criteria andParseTime6EqualTo(Date value) {
            addCriterion("parse_time6 =", value, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6NotEqualTo(Date value) {
            addCriterion("parse_time6 <>", value, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6GreaterThan(Date value) {
            addCriterion("parse_time6 >", value, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6GreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time6 >=", value, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6LessThan(Date value) {
            addCriterion("parse_time6 <", value, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6LessThanOrEqualTo(Date value) {
            addCriterion("parse_time6 <=", value, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6In(List<Date> values) {
            addCriterion("parse_time6 in", values, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6NotIn(List<Date> values) {
            addCriterion("parse_time6 not in", values, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6Between(Date value1, Date value2) {
            addCriterion("parse_time6 between", value1, value2, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime6NotBetween(Date value1, Date value2) {
            addCriterion("parse_time6 not between", value1, value2, "parseTime6");
            return (Criteria) this;
        }

        public Criteria andParseTime7IsNull() {
            addCriterion("parse_time7 is null");
            return (Criteria) this;
        }

        public Criteria andParseTime7IsNotNull() {
            addCriterion("parse_time7 is not null");
            return (Criteria) this;
        }

        public Criteria andParseTime7EqualTo(Date value) {
            addCriterion("parse_time7 =", value, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7NotEqualTo(Date value) {
            addCriterion("parse_time7 <>", value, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7GreaterThan(Date value) {
            addCriterion("parse_time7 >", value, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7GreaterThanOrEqualTo(Date value) {
            addCriterion("parse_time7 >=", value, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7LessThan(Date value) {
            addCriterion("parse_time7 <", value, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7LessThanOrEqualTo(Date value) {
            addCriterion("parse_time7 <=", value, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7In(List<Date> values) {
            addCriterion("parse_time7 in", values, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7NotIn(List<Date> values) {
            addCriterion("parse_time7 not in", values, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7Between(Date value1, Date value2) {
            addCriterion("parse_time7 between", value1, value2, "parseTime7");
            return (Criteria) this;
        }

        public Criteria andParseTime7NotBetween(Date value1, Date value2) {
            addCriterion("parse_time7 not between", value1, value2, "parseTime7");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_user
     *
     * @mbggenerated do_not_delete_during_merge Sat May 16 19:37:46 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gjj_user
     *
     * @mbggenerated Sat May 16 19:37:46 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}